<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['id' => 1, 'code' => '1 ', 'name' => 'Afganistán '],
            ['id' => 2, 'code' => '2 ', 'name' => 'Albania '],
            ['id' => 3, 'code' => '3 ', 'name' => 'Alemania '],
            ['id' => 4, 'code' => '4 ', 'name' => 'Angola '],
            ['id' => 5, 'code' => '5 ', 'name' => 'Antigua y Barbuda '],
            ['id' => 6, 'code' => '6 ', 'name' => 'Arabia Saudita '],
            ['id' => 7, 'code' => '7 ', 'name' => 'Argelia '],
            ['id' => 8, 'code' => '8 ', 'name' => 'Argentina '],
            ['id' => 9, 'code' => '9 ', 'name' => 'Armenia '],
            ['id' => 10, 'code' => '10 ', 'name' => 'Aruba '],
            ['id' => 11, 'code' => '11 ', 'name' => 'Australia '],
            ['id' => 12, 'code' => '12 ', 'name' => 'Austria '],
            ['id' => 13, 'code' => '13 ', 'name' => 'Azerbaiyán '],
            ['id' => 14, 'code' => '14 ', 'name' => 'Bahamas '],
            ['id' => 15, 'code' => '15 ', 'name' => 'Bangladés '],
            ['id' => 16, 'code' => '16 ', 'name' => 'Barbados '],
            ['id' => 17, 'code' => '17 ', 'name' => 'Baréin '],
            ['id' => 18, 'code' => '18 ', 'name' => 'Bélgica '],
            ['id' => 19, 'code' => '19 ', 'name' => 'Belice '],
            ['id' => 20, 'code' => '20 ', 'name' => 'Benín '],
            ['id' => 21, 'code' => '21 ', 'name' => 'Bielorrusia '],
            ['id' => 22, 'code' => '22 ', 'name' => 'Bolivia '],
            ['id' => 23, 'code' => '23 ', 'name' => 'Bonaire, San Eustaquio Y Saba '],
            ['id' => 24, 'code' => '24 ', 'name' => 'Bosnia-Herzegovina '],
            ['id' => 25, 'code' => '25 ', 'name' => 'Botsuana '],
            ['id' => 26, 'code' => '26 ', 'name' => 'Brasil '],
            ['id' => 27, 'code' => '27 ', 'name' => 'Brunéi '],
            ['id' => 28, 'code' => '28 ', 'name' => 'Bulgaria '],
            ['id' => 29, 'code' => '29 ', 'name' => 'Burkina Faso '],
            ['id' => 30, 'code' => '30 ', 'name' => 'Burundi '],
            ['id' => 31, 'code' => '31 ', 'name' => 'Bután '],
            ['id' => 32, 'code' => '32 ', 'name' => 'Cabo Verde '],
            ['id' => 33, 'code' => '33 ', 'name' => 'Camboya '],
            ['id' => 34, 'code' => '34 ', 'name' => 'Camerún '],
            ['id' => 35, 'code' => '35 ', 'name' => 'Canadá '],
            ['id' => 36, 'code' => '36 ', 'name' => 'Chad '],
            ['id' => 37, 'code' => '37 ', 'name' => 'Chile '],
            ['id' => 38, 'code' => '38 ', 'name' => 'China '],
            ['id' => 39, 'code' => '39 ', 'name' => 'Chipre '],
            ['id' => 40, 'code' => '40 ', 'name' => 'Colombia '],
            ['id' => 41, 'code' => '41 ', 'name' => 'Comoras '],
            ['id' => 42, 'code' => '42 ', 'name' => 'Congo '],
            ['id' => 43, 'code' => '43 ', 'name' => 'Corea Del Norte '],
            ['id' => 44, 'code' => '44 ', 'name' => 'Corea Del Sur '],
            ['id' => 45, 'code' => '45 ', 'name' => 'Costa De Marfil '],
            ['id' => 46, 'code' => '46 ', 'name' => 'Costa Rica '],
            ['id' => 47, 'code' => '47 ', 'name' => 'Croacia '],
            ['id' => 48, 'code' => '48 ', 'name' => 'Cuba '],
            ['id' => 49, 'code' => '49 ', 'name' => 'Curazao '],
            ['id' => 50, 'code' => '50 ', 'name' => 'Dinamarca '],
            ['id' => 51, 'code' => '51 ', 'name' => 'Dominica '],
            ['id' => 52, 'code' => '52 ', 'name' => 'Ecuador '],
            ['id' => 53, 'code' => '53 ', 'name' => 'Egipto '],
            ['id' => 54, 'code' => '54 ', 'name' => 'El Salvador '],
            ['id' => 55, 'code' => '55 ', 'name' => 'Emiratos Árabes Unidos '],
            ['id' => 56, 'code' => '56 ', 'name' => 'Eritrea '],
            ['id' => 57, 'code' => '57 ', 'name' => 'Eslovaquia '],
            ['id' => 58, 'code' => '58 ', 'name' => 'Eslovenia '],
            ['id' => 59, 'code' => '59 ', 'name' => 'España '],
            ['id' => 60, 'code' => '60 ', 'name' => 'Estados Unidos '],
            ['id' => 61, 'code' => '61 ', 'name' => 'Estonia '],
            ['id' => 62, 'code' => '62 ', 'name' => 'Etiopía '],
            ['id' => 63, 'code' => '63 ', 'name' => 'Filipinas '],
            ['id' => 64, 'code' => '64 ', 'name' => 'Finlandia '],
            ['id' => 65, 'code' => '65 ', 'name' => 'Fiyi '],
            ['id' => 66, 'code' => '66 ', 'name' => 'Francia '],
            ['id' => 67, 'code' => '67 ', 'name' => 'Gabón '],
            ['id' => 68, 'code' => '68 ', 'name' => 'Gambia '],
            ['id' => 69, 'code' => '69 ', 'name' => 'Georgia '],
            ['id' => 70, 'code' => '70 ', 'name' => 'Ghana '],
            ['id' => 71, 'code' => '71 ', 'name' => 'Grecia '],
            ['id' => 72, 'code' => '72 ', 'name' => 'Groenlandia '],
            ['id' => 73, 'code' => '73 ', 'name' => 'Guadalupe '],
            ['id' => 74, 'code' => '74 ', 'name' => 'Guam '],
            ['id' => 75, 'code' => '75 ', 'name' => 'Guatemala '],
            ['id' => 76, 'code' => '76 ', 'name' => 'Guayana Francesa '],
            ['id' => 77, 'code' => '77 ', 'name' => 'Guernsey '],
            ['id' => 78, 'code' => '78 ', 'name' => 'Guinea '],
            ['id' => 79, 'code' => '79 ', 'name' => 'Guinea Ecuatorial '],
            ['id' => 80, 'code' => '80 ', 'name' => 'Guinea-Bisáu '],
            ['id' => 81, 'code' => '81 ', 'name' => 'Guyana '],
            ['id' => 82, 'code' => '82 ', 'name' => 'Haití '],
            ['id' => 83, 'code' => '83 ', 'name' => 'Honduras '],
            ['id' => 84, 'code' => '84 ', 'name' => 'Hong Kong '],
            ['id' => 85, 'code' => '85 ', 'name' => 'Hungría '],
            ['id' => 86, 'code' => '86 ', 'name' => 'India '],
            ['id' => 87, 'code' => '87 ', 'name' => 'Indonesia '],
            ['id' => 88, 'code' => '88 ', 'name' => 'Irak '],
            ['id' => 89, 'code' => '89 ', 'name' => 'Irán '],
            ['id' => 90, 'code' => '90 ', 'name' => 'Irlanda '],
            ['id' => 91, 'code' => '91 ', 'name' => 'Islandia '],
            ['id' => 92, 'code' => '92 ', 'name' => 'Islas Caimán '],
            ['id' => 93, 'code' => '93 ', 'name' => 'Islas Vírgenes Británicas '],
            ['id' => 94, 'code' => '94 ', 'name' => 'Israel '],
            ['id' => 95, 'code' => '95 ', 'name' => 'Italia '],
            ['id' => 96, 'code' => '96 ', 'name' => 'Jamaica '],
            ['id' => 97, 'code' => '97 ', 'name' => 'Japón '],
            ['id' => 98, 'code' => '98 ', 'name' => 'Jersey '],
            ['id' => 99, 'code' => '99 ', 'name' => 'Jordania '],
            ['id' => 100, 'code' => '100 ', 'name' => 'Kazajistán '],
            ['id' => 101, 'code' => '101 ', 'name' => 'Kenia '],
            ['id' => 102, 'code' => '102 ', 'name' => 'Kirguistán '],
            ['id' => 103, 'code' => '103 ', 'name' => 'Kuwait '],
            ['id' => 104, 'code' => '104 ', 'name' => 'Laos '],
            ['id' => 105, 'code' => '105 ', 'name' => 'Lesoto '],
            ['id' => 106, 'code' => '106 ', 'name' => 'Letonia '],
            ['id' => 107, 'code' => '107 ', 'name' => 'Líbano '],
            ['id' => 108, 'code' => '108 ', 'name' => 'Liberia '],
            ['id' => 109, 'code' => '109 ', 'name' => 'Libia '],
            ['id' => 110, 'code' => '110 ', 'name' => 'Liechtenstein '],
            ['id' => 111, 'code' => '111 ', 'name' => 'Lituania '],
            ['id' => 112, 'code' => '112 ', 'name' => 'Luxemburgo '],
            ['id' => 113, 'code' => '113 ', 'name' => 'Macedonia, La Antigua Republicayugoslava De '],
            ['id' => 114, 'code' => '114 ', 'name' => 'Madagascar '],
            ['id' => 115, 'code' => '115 ', 'name' => 'Malasia '],
            ['id' => 116, 'code' => '116 ', 'name' => 'Malaui '],
            ['id' => 117, 'code' => '117 ', 'name' => 'Maldivas '],
            ['id' => 118, 'code' => '118 ', 'name' => 'Malí '],
            ['id' => 119, 'code' => '119 ', 'name' => 'Malta '],
            ['id' => 120, 'code' => '120 ', 'name' => 'Marruecos '],
            ['id' => 121, 'code' => '121 ', 'name' => 'MARSHALL, ISLAS '],
            ['id' => 122, 'code' => '122 ', 'name' => 'Martinica '],
            ['id' => 123, 'code' => '123 ', 'name' => 'Mauricio '],
            ['id' => 124, 'code' => '124 ', 'name' => 'Mauritania '],
            ['id' => 125, 'code' => '125 ', 'name' => 'Mayotte '],
            ['id' => 126, 'code' => '126 ', 'name' => 'México '],
            ['id' => 127, 'code' => '127 ', 'name' => 'Moldavia '],
            ['id' => 128, 'code' => '128 ', 'name' => 'Mónaco '],
            ['id' => 129, 'code' => '129 ', 'name' => 'Mongolia '],
            ['id' => 130, 'code' => '130 ', 'name' => 'Montenegro '],
            ['id' => 131, 'code' => '131 ', 'name' => 'Mozambique '],
            ['id' => 132, 'code' => '132 ', 'name' => 'Namibia '],
            ['id' => 133, 'code' => '133 ', 'name' => 'Nauru '],
            ['id' => 134, 'code' => '134 ', 'name' => 'Nepal '],
            ['id' => 135, 'code' => '135 ', 'name' => 'Nicaragua '],
            ['id' => 136, 'code' => '136 ', 'name' => 'Níger '],
            ['id' => 137, 'code' => '137 ', 'name' => 'Nigeria '],
            ['id' => 138, 'code' => '138 ', 'name' => 'Niue '],
            ['id' => 139, 'code' => '139 ', 'name' => 'Noruega '],
            ['id' => 140, 'code' => '140 ', 'name' => 'Nueva Caledonia '],
            ['id' => 141, 'code' => '141 ', 'name' => 'Nueva Zelanda '],
            ['id' => 142, 'code' => '142 ', 'name' => 'Omán '],
            ['id' => 143, 'code' => '143 ', 'name' => 'Países Bajos '],
            ['id' => 144, 'code' => '144 ', 'name' => 'Pakistán '],
            ['id' => 145, 'code' => '145 ', 'name' => 'Palaos '],
            ['id' => 146, 'code' => '146 ', 'name' => 'Palestina '],
            ['id' => 147, 'code' => '147 ', 'name' => 'Panamá '],
            ['id' => 148, 'code' => '148 ', 'name' => 'Papúa Nueva Guinea '],
            ['id' => 149, 'code' => '149 ', 'name' => 'Paraguay '],
            ['id' => 150, 'code' => '150 ', 'name' => 'Perú '],
            ['id' => 151, 'code' => '151 ', 'name' => 'Pitcairn '],
            ['id' => 152, 'code' => '152 ', 'name' => 'Polinesia Francesa '],
            ['id' => 153, 'code' => '153 ', 'name' => 'Polonia '],
            ['id' => 154, 'code' => '154 ', 'name' => 'Portugal '],
            ['id' => 155, 'code' => '155 ', 'name' => 'Puerto Rico '],
            ['id' => 156, 'code' => '156 ', 'name' => 'Qatar '],
            ['id' => 157, 'code' => '157 ', 'name' => 'Reino Unido '],
            ['id' => 158, 'code' => '158 ', 'name' => 'República Centroafricana '],
            ['id' => 159, 'code' => '159 ', 'name' => 'República Checa '],
            ['id' => 160, 'code' => '160 ', 'name' => 'República Democrática Del Congo '],
            ['id' => 161, 'code' => '161 ', 'name' => 'República Dominicana '],
            ['id' => 162, 'code' => '162 ', 'name' => 'Ruanda '],
            ['id' => 163, 'code' => '163 ', 'name' => 'Rumania '],
            ['id' => 164, 'code' => '164 ', 'name' => 'Rusia '],
            ['id' => 165, 'code' => '165 ', 'name' => 'Sahara Occidental '],
            ['id' => 166, 'code' => '166 ', 'name' => 'Samoa '],
            ['id' => 167, 'code' => '167 ', 'name' => 'Samoa Americana '],
            ['id' => 168, 'code' => '168 ', 'name' => 'San Bartolome '],
            ['id' => 169, 'code' => '169 ', 'name' => 'San Cristóbal Y Nieves '],
            ['id' => 170, 'code' => '170 ', 'name' => 'San Marino '],
            ['id' => 171, 'code' => '171 ', 'name' => 'San Martin (Parte Francesa) '],
            ['id' => 172, 'code' => '172 ', 'name' => 'San Pedro Y Miquelon '],
            ['id' => 173, 'code' => '173 ', 'name' => 'San Vicente Y Las Granadinas '],
            ['id' => 174, 'code' => '174 ', 'name' => 'Santa Helena, Ascension Y Tristan De Acuña '],
            ['id' => 175, 'code' => '175 ', 'name' => 'Santa Lucía '],
            ['id' => 176, 'code' => '176 ', 'name' => 'Santo Tomé Y Príncipe '],
            ['id' => 177, 'code' => '177 ', 'name' => 'Senegal '],
            ['id' => 178, 'code' => '178 ', 'name' => 'Serbia '],
            ['id' => 179, 'code' => '179 ', 'name' => 'Seychelles '],
            ['id' => 180, 'code' => '180 ', 'name' => 'Sierra Leona '],
            ['id' => 181, 'code' => '181 ', 'name' => 'Singapur '],
            ['id' => 182, 'code' => '182 ', 'name' => 'Sint Maarten (Parte Neerlandesa) '],
            ['id' => 183, 'code' => '183 ', 'name' => 'Siria '],
            ['id' => 184, 'code' => '184 ', 'name' => 'Somalia '],
            ['id' => 185, 'code' => '185 ', 'name' => 'Sri Lanka '],
            ['id' => 186, 'code' => '186 ', 'name' => 'Suazilandia '],
            ['id' => 187, 'code' => '187 ', 'name' => 'Sudáfrica '],
            ['id' => 188, 'code' => '188 ', 'name' => 'Sudán '],
            ['id' => 189, 'code' => '189 ', 'name' => 'Sudán Del Sur '],
            ['id' => 190, 'code' => '190 ', 'name' => 'Suecia '],
            ['id' => 191, 'code' => '191 ', 'name' => 'Suiza '],
            ['id' => 192, 'code' => '192 ', 'name' => 'Surinam '],
            ['id' => 193, 'code' => '193 ', 'name' => 'Svalbard Y Jan Mayen '],
            ['id' => 194, 'code' => '194 ', 'name' => 'Tailandia '],
            ['id' => 195, 'code' => '195 ', 'name' => 'Taiwán '],
            ['id' => 196, 'code' => '196 ', 'name' => 'Tanzania '],
            ['id' => 197, 'code' => '197 ', 'name' => 'Tayikistán '],
            ['id' => 198, 'code' => '198 ', 'name' => 'Territorio Britanico Del Oceano Indico '],
            ['id' => 199, 'code' => '199 ', 'name' => 'Territorios Australes Franceses '],
            ['id' => 200, 'code' => '200 ', 'name' => 'Timor Oriental '],
            ['id' => 201, 'code' => '201 ', 'name' => 'Togo '],
            ['id' => 202, 'code' => '202 ', 'name' => 'Tokelau '],
            ['id' => 203, 'code' => '203 ', 'name' => 'Tonga '],
            ['id' => 204, 'code' => '204 ', 'name' => 'Trinidad Y Tobago '],
            ['id' => 205, 'code' => '205 ', 'name' => 'Túnez '],
            ['id' => 206, 'code' => '206 ', 'name' => 'Turkmenistán '],
            ['id' => 207, 'code' => '207 ', 'name' => 'Turquía '],
            ['id' => 208, 'code' => '208 ', 'name' => 'Tuvalu '],
            ['id' => 209, 'code' => '209 ', 'name' => 'Ucrania '],
            ['id' => 210, 'code' => '210 ', 'name' => 'Uganda '],
            ['id' => 211, 'code' => '211 ', 'name' => 'Uruguay '],
            ['id' => 212, 'code' => '212 ', 'name' => 'Uzbekistán '],
            ['id' => 213, 'code' => '213 ', 'name' => 'Vanuatu '],
            ['id' => 214, 'code' => '214 ', 'name' => 'Vaticano '],
            ['id' => 215, 'code' => '215 ', 'name' => 'Venezuela '],
            ['id' => 216, 'code' => '216 ', 'name' => 'Vietnam '],
            ['id' => 217, 'code' => '217 ', 'name' => 'Wallis Y Futuna '],
            ['id' => 218, 'code' => '218 ', 'name' => 'Yemen '],
            ['id' => 219, 'code' => '219 ', 'name' => 'Yibuti '],
            ['id' => 220, 'code' => '220 ', 'name' => 'Zambia '],
            ['id' => 221, 'code' => '221 ', 'name' => 'Zimbabue ']


        ]);

        
    }
}
