<?php

namespace Database\Seeders;

use App\Models\MeasurementUnit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('measurement_units')->insert([
            ['id' => 1, 'code' => '10 ', 'name' => 'Grupo '],
            ['id' => 2, 'code' => '11 ', 'name' => 'Equipar '],
            ['id' => 3, 'code' => '13 ', 'name' => 'Ración '],
            ['id' => 4, 'code' => '14 ', 'name' => 'Disparo '],
            ['id' => 5, 'code' => '15 ', 'name' => 'Palo '],
            ['id' => 6, 'code' => '16 ', 'name' => 'Tambor De Ciento Quince Kg '],
            ['id' => 7, 'code' => '17 ', 'name' => 'Tambor De Cien Libras '],
            ['id' => 8, 'code' => '18 ', 'name' => 'Tambor De Cincuenta Y Cinco Galones (Us) '],
            ['id' => 9, 'code' => '19 ', 'name' => 'Camión Cisterna '],
            ['id' => 10, 'code' => '20 ', 'name' => 'Contenedor De Veinte Pies '],
            ['id' => 11, 'code' => '21 ', 'name' => 'Contenedor De Cuarenta Pies '],
            ['id' => 12, 'code' => '22 ', 'name' => 'Decilitro Por Gramo '],
            ['id' => 13, 'code' => '23 ', 'name' => 'Gramo Por Centímetro Cúbico '],
            ['id' => 14, 'code' => '24 ', 'name' => 'Libra Teórica '],
            ['id' => 15, 'code' => '25 ', 'name' => 'Gramo Por Centímetro Cuadrado '],
            ['id' => 16, 'code' => '26 ', 'name' => 'Tonelada Real '],
            ['id' => 17, 'code' => '27 ', 'name' => 'Tonelada Teórica '],
            ['id' => 18, 'code' => '28 ', 'name' => 'Kilogramo Por Metro Cuadrado '],
            ['id' => 19, 'code' => '29 ', 'name' => 'Libra Por Mil Pies Cuadrados '],
            ['id' => 20, 'code' => '30 ', 'name' => 'Día De Potencia Del Caballo Por Tonelada Métrica Seca Al Aire. '],
            ['id' => 21, 'code' => '31 ', 'name' => 'Coger Peso '],
            ['id' => 22, 'code' => '32 ', 'name' => 'Kilogramo Por Aire Seco Tonelada Métrica '],
            ['id' => 23, 'code' => '33 ', 'name' => 'Kilopascales Metros Cuadrados Por Gramo '],
            ['id' => 24, 'code' => '34 ', 'name' => 'Kilopascales Por Milímetro '],
            ['id' => 25, 'code' => '35 ', 'name' => 'Mililitros Por Centímetro Cuadrado Segundo '],
            ['id' => 26, 'code' => '36 ', 'name' => 'Pies Cúbicos Por Minuto Por Pie Cuadrado '],
            ['id' => 27, 'code' => '37 ', 'name' => 'Onza Por Pie Cuadrado '],
            ['id' => 28, 'code' => '38 ', 'name' => 'Onzas Por Pie Cuadrado Por 0,01 Pulgadas '],
            ['id' => 29, 'code' => '40 ', 'name' => 'Mililitro Por Segundo '],
            ['id' => 30, 'code' => '41 ', 'name' => 'Mililitro Por Minuto '],
            ['id' => 31, 'code' => '43 ', 'name' => 'Bolsa Súper A Granel '],
            ['id' => 32, 'code' => '44 ', 'name' => 'Bolsa A Granel De Quinientos Kg '],
            ['id' => 33, 'code' => '45 ', 'name' => 'Bolsa A Granel De Trescientos Kg '],
            ['id' => 34, 'code' => '46 ', 'name' => 'Bolsa A Granel De Cincuenta Libras '],
            ['id' => 35, 'code' => '47 ', 'name' => 'Bolsa De Cincuenta Libras '],
            ['id' => 36, 'code' => '48 ', 'name' => 'Carga De Automóviles A Granel '],
            ['id' => 37, 'code' => '53 ', 'name' => 'Kilogramos Teóricos '],
            ['id' => 38, 'code' => '54 ', 'name' => 'Tonelada Teórica '],
            ['id' => 39, 'code' => '56 ', 'name' => 'Sitas '],
            ['id' => 40, 'code' => '57 ', 'name' => 'Malla '],
            ['id' => 41, 'code' => '58 ', 'name' => 'Kilogramo Neto '],
            ['id' => 42, 'code' => '59 ', 'name' => 'Parte Por Millón '],
            ['id' => 43, 'code' => '60 ', 'name' => 'Porcentaje De Peso '],
            ['id' => 44, 'code' => '61 ', 'name' => 'Parte Por Billón (Us) '],
            ['id' => 45, 'code' => '62 ', 'name' => 'Porcentaje Por 1000 Horas '],
            ['id' => 46, 'code' => '63 ', 'name' => 'Tasa De Fracaso En El Tiempo '],
            ['id' => 47, 'code' => '64 ', 'name' => 'Libra Por Pulgada Cuadrada, Calibre '],
            ['id' => 48, 'code' => '66 ', 'name' => 'Oersted '],
            ['id' => 49, 'code' => '69 ', 'name' => 'Prueba De Escala Específica '],
            ['id' => 50, 'code' => '71 ', 'name' => 'Voltio Amperio Por Libra '],
            ['id' => 51, 'code' => '72 ', 'name' => 'Vatio Por Libra '],
            ['id' => 52, 'code' => '73 ', 'name' => 'Amperio Tum Por Centímetro '],
            ['id' => 53, 'code' => '74 ', 'name' => 'Milipascal '],
            ['id' => 54, 'code' => '76 ', 'name' => 'Gauss '],
            ['id' => 55, 'code' => '77 ', 'name' => 'Mili Pulgadas '],
            ['id' => 56, 'code' => '78 ', 'name' => 'Kilogauss '],
            ['id' => 57, 'code' => '80 ', 'name' => 'Libras Por Pulgada Cuadrada Absoluta '],
            ['id' => 58, 'code' => '81 ', 'name' => 'Enrique '],
            ['id' => 59, 'code' => '84 ', 'name' => 'Kilopound Por Pulgada Cuadrada '],
            ['id' => 60, 'code' => '85 ', 'name' => 'Fuerza Libra Pie '],
            ['id' => 61, 'code' => '87 ', 'name' => 'Libra Por Pie Cúbico '],
            ['id' => 62, 'code' => '89 ', 'name' => 'Equilibrio '],
            ['id' => 63, 'code' => '90 ', 'name' => 'Saybold Segundo Universal '],
            ['id' => 64, 'code' => '91 ', 'name' => 'Alimenta '],
            ['id' => 65, 'code' => '92 ', 'name' => 'Calorías Por Centímetro Cúbico '],
            ['id' => 66, 'code' => '93 ', 'name' => 'Calorías Por Gramo '],
            ['id' => 67, 'code' => '94 ', 'name' => 'Unidad '],
            ['id' => 68, 'code' => '95 ', 'name' => 'Veinte Mil Galones (Us) De Carros '],
            ['id' => 69, 'code' => '96 ', 'name' => 'Diez Mil Galones (Us) De Carros '],
            ['id' => 70, 'code' => '97 ', 'name' => 'Tambor De Diez Kg '],
            ['id' => 71, 'code' => '98 ', 'name' => 'Tambor De Quince Kg '],
            ['id' => 72, 'code' => '04 ', 'name' => 'Spray Pequeños '],
            ['id' => 73, 'code' => '05 ', 'name' => 'Levantar '],
            ['id' => 74, 'code' => '08 ', 'name' => 'Lote Calor '],
            ['id' => 75, 'code' => '1A ', 'name' => 'Milla De Coche '],
            ['id' => 76, 'code' => '1B ', 'name' => 'Recuento De Coches '],
            ['id' => 77, 'code' => '1C ', 'name' => 'Recuento De Locomotoras '],
            ['id' => 78, 'code' => '1D ', 'name' => 'Recuento De Cabos '],
            ['id' => 79, 'code' => '1E ', 'name' => 'Carro Vacio '],
            ['id' => 80, 'code' => '1F ', 'name' => 'Millas De Tren '],
            ['id' => 81, 'code' => '1G ', 'name' => 'Uso De Combustible Galón (Us) '],
            ['id' => 82, 'code' => '1H ', 'name' => 'Milla Del Caboose '],
            ['id' => 83, 'code' => '1I ', 'name' => 'Tipo De Interés Fijo '],
            ['id' => 84, 'code' => '1J ', 'name' => 'Tonelada Milla '],
            ['id' => 85, 'code' => '1K ', 'name' => 'Milla Locomotora '],
            ['id' => 86, 'code' => '1L ', 'name' => 'Recuento Total De Coches '],
            ['id' => 87, 'code' => '1M ', 'name' => 'Milla De Coche Total '],
            ['id' => 88, 'code' => '1X ', 'name' => 'Cuarto De Milla '],
            ['id' => 89, 'code' => '2A ', 'name' => 'Radianes Por Segundo '],
            ['id' => 90, 'code' => '2B ', 'name' => 'Radianes Por Segundo Al Cuadrado '],
            ['id' => 91, 'code' => '2C ', 'name' => 'Röntgen '],
            ['id' => 92, 'code' => '2I ', 'name' => 'Unidad Térmica Británica Por Hora. '],
            ['id' => 93, 'code' => '2J ', 'name' => 'Centímetro Cúbico Por Segundo '],
            ['id' => 94, 'code' => '2K ', 'name' => 'Pie Cúbico Por Hora '],
            ['id' => 95, 'code' => '2L ', 'name' => 'Pie Cúbico Por Minuto '],
            ['id' => 96, 'code' => '2M ', 'name' => 'Centímetro Por Segundo '],
            ['id' => 97, 'code' => '2N ', 'name' => 'Decibel '],
            ['id' => 98, 'code' => '2P ', 'name' => 'Kilobyte '],
            ['id' => 99, 'code' => '2Q ', 'name' => 'Kilobecquerel '],
            ['id' => 100, 'code' => '2R ', 'name' => 'Kilocurie '],
            ['id' => 101, 'code' => '2U ', 'name' => 'Megagramo '],
            ['id' => 102, 'code' => '2V ', 'name' => 'Megagramo Por Hora '],
            ['id' => 103, 'code' => '2W ', 'name' => 'Compartimiento '],
            ['id' => 104, 'code' => '2X ', 'name' => 'Metro Por Minuto '],
            ['id' => 105, 'code' => '2Y ', 'name' => 'Milliröntgen '],
            ['id' => 106, 'code' => '2Z ', 'name' => 'Milivoltios '],
            ['id' => 107, 'code' => '3B ', 'name' => 'Megajulio '],
            ['id' => 108, 'code' => '3C ', 'name' => 'Manmonth '],
            ['id' => 109, 'code' => '3E ', 'name' => 'Libra Por Libra De Producto '],
            ['id' => 110, 'code' => '3G ', 'name' => 'Libra Por Pieza De Producto '],
            ['id' => 111, 'code' => '3H ', 'name' => 'Kilogramo Por Kilogramo De Producto '],
            ['id' => 112, 'code' => '3I ', 'name' => 'Kilogramo Por Pieza De Producto '],
            ['id' => 113, 'code' => '4A ', 'name' => 'Bobina '],
            ['id' => 114, 'code' => '4B ', 'name' => 'Gorra '],
            ['id' => 115, 'code' => '4C ', 'name' => 'Centistokes '],
            ['id' => 116, 'code' => '4E ', 'name' => 'Paquete De Veinte '],
            ['id' => 117, 'code' => '4G ', 'name' => 'Microlitro '],
            ['id' => 118, 'code' => '4H ', 'name' => 'Micrometro '],
            ['id' => 119, 'code' => '4K ', 'name' => 'Miliamperio '],
            ['id' => 120, 'code' => '4L ', 'name' => 'Megabyte '],
            ['id' => 121, 'code' => '4M ', 'name' => 'Miligramo Por Hora '],
            ['id' => 122, 'code' => '4N ', 'name' => 'Megabecquerel '],
            ['id' => 123, 'code' => '4O ', 'name' => 'Microfarad '],
            ['id' => 124, 'code' => '4P ', 'name' => 'Newton Por Metro '],
            ['id' => 125, 'code' => '4Q ', 'name' => 'Onza Pulgada '],
            ['id' => 126, 'code' => '4R ', 'name' => 'Pie Onza '],
            ['id' => 127, 'code' => '4T ', 'name' => 'Picofarad '],
            ['id' => 128, 'code' => '4U ', 'name' => 'Libra Por Hora '],
            ['id' => 129, 'code' => '4W ', 'name' => 'Tonelada (Us) Por Hora '],
            ['id' => 130, 'code' => '4X ', 'name' => 'Kilolitro Por Hora '],
            ['id' => 131, 'code' => 'BTU ', 'name' => 'Unidad Térmica Británica '],
            ['id' => 132, 'code' => 'BUA ', 'name' => 'Bushel (Ee. Uu.) '],
            ['id' => 133, 'code' => 'BUI ', 'name' => 'Bushel (Reino Unido) '],
            ['id' => 134, 'code' => 'BW ', 'name' => 'Peso Base '],
            ['id' => 135, 'code' => 'BX ', 'name' => 'Caja '],
            ['id' => 136, 'code' => 'BZ ', 'name' => 'Millones De Btus '],
            ['id' => 137, 'code' => 'C0 ', 'name' => 'Llamada '],
            ['id' => 138, 'code' => 'C1 ', 'name' => 'Producto Compuesto Libra (Peso Total) '],
            ['id' => 139, 'code' => 'C10 ', 'name' => 'Millifarad '],
            ['id' => 140, 'code' => 'C11 ', 'name' => 'Miligal '],
            ['id' => 141, 'code' => 'C12 ', 'name' => 'Miligramo Por Metro '],
            ['id' => 142, 'code' => 'C13 ', 'name' => 'Miligray '],
            ['id' => 143, 'code' => 'C14 ', 'name' => 'Milihenry '],
            ['id' => 144, 'code' => 'C15 ', 'name' => 'Milijoule '],
            ['id' => 145, 'code' => 'C16 ', 'name' => 'Milímetro Por Segundo '],
            ['id' => 146, 'code' => 'C17 ', 'name' => 'Milímetro Cuadrado Por Segundo '],
            ['id' => 147, 'code' => 'C18 ', 'name' => 'Milimol '],
            ['id' => 148, 'code' => 'C19 ', 'name' => 'Mol Por Kilogramo '],
            ['id' => 149, 'code' => 'C2 ', 'name' => 'Carset '],
            ['id' => 150, 'code' => 'C20 ', 'name' => 'Millinewton '],
            ['id' => 151, 'code' => 'C22 ', 'name' => 'Millinewton Por Metro '],
            ['id' => 152, 'code' => 'C23 ', 'name' => 'Medidor De Miliohm '],
            ['id' => 153, 'code' => 'C24 ', 'name' => 'Segundo Milipascal '],
            ['id' => 154, 'code' => 'C25 ', 'name' => 'Miliradian '],
            ['id' => 155, 'code' => 'C26 ', 'name' => 'Milisegundo '],
            ['id' => 156, 'code' => 'C27 ', 'name' => 'Milisiemens '],
            ['id' => 157, 'code' => 'C28 ', 'name' => 'Milisievert '],
            ['id' => 158, 'code' => 'C29 ', 'name' => 'Millitesla '],
            ['id' => 159, 'code' => 'C3 ', 'name' => 'Microvoltios Por Metro '],
            ['id' => 160, 'code' => 'INK ', 'name' => 'Pulgada Cuadrada '],
            ['id' => 161, 'code' => 'INQ ', 'name' => 'Pulgada En Cubos '],
            ['id' => 162, 'code' => 'IP ', 'name' => 'Póliza De Seguros '],
            ['id' => 163, 'code' => 'IT ', 'name' => 'Conteo Por Centímetro '],
            ['id' => 164, 'code' => 'IU ', 'name' => 'Pulgada Por Segundo (Velocidad Lineal) '],
            ['id' => 165, 'code' => 'IV ', 'name' => 'Pulgada Por Segundo Al Cuadrado (Aceleración) '],
            ['id' => 166, 'code' => 'J2 ', 'name' => 'Julios Por Kilogramo '],
            ['id' => 167, 'code' => 'JB ', 'name' => 'Jumbo '],
            ['id' => 168, 'code' => 'JE ', 'name' => 'Joule Por Kelvin '],
            ['id' => 169, 'code' => 'JG ', 'name' => 'Jarra '],
            ['id' => 170, 'code' => 'JK ', 'name' => 'Megajulio Por Kilogramo '],
            ['id' => 171, 'code' => 'JM ', 'name' => 'Megajulio Por Metro Cúbico '],
            ['id' => 172, 'code' => 'JO ', 'name' => 'Articulación '],
            ['id' => 173, 'code' => 'JOU ', 'name' => 'Joule '],
            ['id' => 174, 'code' => 'JR ', 'name' => 'Tarro '],
            ['id' => 175, 'code' => 'K1 ', 'name' => 'Demanda De Kilovatios '],
            ['id' => 176, 'code' => 'K2 ', 'name' => 'Kilovoltios Amperios Reactivos De Demanda '],
            ['id' => 177, 'code' => 'K3 ', 'name' => 'Kilovoltio Amperio Hora Reactiva '],
            ['id' => 178, 'code' => 'K5 ', 'name' => 'Amperios Kilovoltios (Reactivos) '],
            ['id' => 179, 'code' => 'K6 ', 'name' => 'Kilolitro '],
            ['id' => 180, 'code' => 'KA ', 'name' => 'Pastel '],
            ['id' => 181, 'code' => 'KB ', 'name' => 'Kilocharacter '],
            ['id' => 182, 'code' => 'KBA ', 'name' => 'Kilobar '],
            ['id' => 183, 'code' => 'KD ', 'name' => 'Kilogramo Decimal '],
            ['id' => 184, 'code' => 'KEL ', 'name' => 'Kelvin '],
            ['id' => 185, 'code' => 'KF ', 'name' => 'Kilopacket '],
            ['id' => 186, 'code' => 'KG ', 'name' => 'Barrilete '],
            ['id' => 187, 'code' => 'KGM ', 'name' => 'Kilogramo '],
            ['id' => 188, 'code' => 'KGS ', 'name' => 'Kilogramo Por Segundo '],
            ['id' => 189, 'code' => 'KHZ ', 'name' => 'Kilohercio '],
            ['id' => 190, 'code' => '5A ', 'name' => 'Barril Por Minuto '],
            ['id' => 191, 'code' => '5B ', 'name' => 'Lote '],
            ['id' => 192, 'code' => '5C ', 'name' => 'Galón (Us) Por Mil '],
            ['id' => 193, 'code' => '5E ', 'name' => 'Mmscf / Día '],
            ['id' => 194, 'code' => '5F ', 'name' => 'Libras Por Mil '],
            ['id' => 195, 'code' => '5G ', 'name' => 'Bomba '],
            ['id' => 196, 'code' => '5H ', 'name' => 'Escenario '],
            ['id' => 197, 'code' => '5I ', 'name' => 'Pie Cúbico Estándar '],
            ['id' => 198, 'code' => '5J ', 'name' => 'Potencia Hidráulica De Caballos '],
            ['id' => 199, 'code' => '5K ', 'name' => 'Contar Por Minuto '],
            ['id' => 200, 'code' => '5P ', 'name' => 'Nivel Sismico '],
            ['id' => 201, 'code' => '5Q ', 'name' => '260Nfor Sismica '],
            ['id' => 202, 'code' => 'A1 ', 'name' => '15 Calorías C '],
            ['id' => 203, 'code' => 'A10 ', 'name' => 'Amperio Metro Cuadrado Por Joule Segundo '],
            ['id' => 204, 'code' => 'A11 ', 'name' => 'Ã ¥ Ngström '],
            ['id' => 205, 'code' => 'A12 ', 'name' => 'Unidad Astronómica '],
            ['id' => 206, 'code' => 'A13 ', 'name' => 'Attojoule '],
            ['id' => 207, 'code' => 'A14 ', 'name' => 'Granero '],
            ['id' => 208, 'code' => 'A15 ', 'name' => 'Granero Por Electrón Voltio '],
            ['id' => 209, 'code' => 'A16 ', 'name' => 'Granero Por Voltio De Electrones Esteradiano, '],
            ['id' => 210, 'code' => 'A17 ', 'name' => 'Granero Por Sterdian '],
            ['id' => 211, 'code' => 'A18 ', 'name' => 'Becquerel Por Kilogramo '],
            ['id' => 212, 'code' => 'A19 ', 'name' => 'Becquerel Por Metro Cúbico '],
            ['id' => 213, 'code' => 'A2 ', 'name' => 'Amperio Por Centímetro '],
            ['id' => 214, 'code' => 'A20 ', 'name' => 'Unidad Térmica Británica Por Segundo Pie Cuadrado Grado Rankin '],
            ['id' => 215, 'code' => 'A21 ', 'name' => 'Unidad Térmica Británica Por Libra Grado Rankin '],
            ['id' => 216, 'code' => 'A22 ', 'name' => 'Unidad Térmica Británica Por Segundo Pie Grado Rankin '],
            ['id' => 217, 'code' => 'A23 ', 'name' => 'Unidad Térmica Británica Por Hora Pie Cuadrado Grado Rankin '],
            ['id' => 218, 'code' => 'A24 ', 'name' => 'Candela Por Metro Cuadrado '],
            ['id' => 219, 'code' => 'A25 ', 'name' => 'Cheval Vapeur '],
            ['id' => 220, 'code' => 'A26 ', 'name' => 'Medidor De Culombio '],
            ['id' => 221, 'code' => 'A27 ', 'name' => 'Medidor De Culombio Al Cuadrado Por Voltio '],
            ['id' => 222, 'code' => 'A28 ', 'name' => 'Coulomb Por Centímetro Cúbico '],
            ['id' => 223, 'code' => 'A29 ', 'name' => 'Coulomb Por Metro Cúbico '],
            ['id' => 224, 'code' => 'A3 ', 'name' => 'Amperio Por Milímetro '],
            ['id' => 225, 'code' => 'A30 ', 'name' => 'Coulomb Por Milímetro Cúbico '],
            ['id' => 226, 'code' => 'A31 ', 'name' => 'Coulomb Por Kilogramo Segundo '],
            ['id' => 227, 'code' => 'A32 ', 'name' => 'Coulomb Por Mol '],
            ['id' => 228, 'code' => 'A33 ', 'name' => 'Coulomb Por Centímetro Cuadrado '],
            ['id' => 229, 'code' => 'A34 ', 'name' => 'Coulomb Por Metro Cuadrado '],
            ['id' => 230, 'code' => 'A35 ', 'name' => 'Coulomb Por Milímetro Cuadrado '],
            ['id' => 231, 'code' => 'A36 ', 'name' => 'Centímetro Cúbico Por Mol '],
            ['id' => 232, 'code' => 'A37 ', 'name' => '261Nformaci Cúbico Por Mol '],
            ['id' => 233, 'code' => 'A38 ', 'name' => 'Metro Cúbico Por Coulomb '],
            ['id' => 234, 'code' => 'A39 ', 'name' => 'Metro Cúbico Por Kilogramo '],
            ['id' => 235, 'code' => 'A4 ', 'name' => 'Amperio Por Centímetro Cuadrado '],
            ['id' => 236, 'code' => 'A40 ', 'name' => 'Metro Cúbico Por Mol '],
            ['id' => 237, 'code' => 'A41 ', 'name' => 'Amperio Por Metro Cuadrado '],
            ['id' => 238, 'code' => 'A42 ', 'name' => 'Curie Por Kilogramo '],
            ['id' => 239, 'code' => 'A43 ', 'name' => 'Tonelaje De Peso Muerto '],
            ['id' => 240, 'code' => 'A44 ', 'name' => 'Decalitro '],
            ['id' => 241, 'code' => 'A45 ', 'name' => 'Decámetro '],
            ['id' => 242, 'code' => 'A47 ', 'name' => 'Decitex '],
            ['id' => 243, 'code' => 'A48 ', 'name' => 'Grado Rankin '],
            ['id' => 244, 'code' => 'A49 ', 'name' => 'Negador '],
            ['id' => 245, 'code' => 'A5 ', 'name' => 'Amperio Metro Cuadrado '],
            ['id' => 246, 'code' => 'A50 ', 'name' => 'Dyn Segundo Por Centímetro Cúbico '],
            ['id' => 247, 'code' => 'A51 ', 'name' => 'Dina Segundo Por Centímetro '],
            ['id' => 248, 'code' => 'A52 ', 'name' => 'Dina Segundo Por Centímetro Al Quinto '],
            ['id' => 249, 'code' => 'A53 ', 'name' => 'Electronvolt '],
            ['id' => 250, 'code' => 'A54 ', 'name' => 'Electronvoltio Por Metro '],
            ['id' => 251, 'code' => 'A55 ', 'name' => 'Metro Electronvolt Cuadrado '],
            ['id' => 252, 'code' => 'A56 ', 'name' => 'Electronvoltio De Metro Cuadrado Por Kilogramo '],
            ['id' => 253, 'code' => 'A57 ', 'name' => 'Ergio '],
            ['id' => 254, 'code' => 'A58 ', 'name' => 'Erg Por Centímetro '],
            ['id' => 255, 'code' => 'A6 ', 'name' => 'Amperio Por Metro Cuadrado Kelvin Al Cuadrado '],
            ['id' => 256, 'code' => 'A60 ', 'name' => 'Erg Por Centímetro Cúbico '],
            ['id' => 257, 'code' => 'A61 ', 'name' => 'Erg Por Gramo '],
            ['id' => 258, 'code' => 'A62 ', 'name' => 'Erg Por Gramo De Segundo '],
            ['id' => 259, 'code' => 'A63 ', 'name' => 'Erg Por Segundo '],
            ['id' => 260, 'code' => 'A64 ', 'name' => 'Erg Por Segundo Centímetro Cuadrado '],
            ['id' => 261, 'code' => 'A65 ', 'name' => 'Erg Por Centímetro Cuadrado Segundo '],
            ['id' => 262, 'code' => 'A66 ', 'name' => 'Erg Centímetro Cuadrado '],
            ['id' => 263, 'code' => 'A67 ', 'name' => 'Ergímetro Cuadrado Por Gramo '],
            ['id' => 264, 'code' => 'A68 ', 'name' => 'Exajulio '],
            ['id' => 265, 'code' => 'A69 ', 'name' => 'Faradio Por Metro '],
            ['id' => 266, 'code' => 'A7 ', 'name' => 'Amperio Por Milímetro Cuadrado '],
            ['id' => 267, 'code' => 'A70 ', 'name' => 'Femtojoule '],
            ['id' => 268, 'code' => 'A71 ', 'name' => 'Femtometro '],
            ['id' => 269, 'code' => 'A73 ', 'name' => 'Pie Por Segundo Al Cuadrado '],
            ['id' => 270, 'code' => 'A74 ', 'name' => 'Pie-Fuerza De La Libra Por Segundo '],
            ['id' => 271, 'code' => 'A75 ', 'name' => 'Tonelada De Carga '],
            ['id' => 272, 'code' => 'A76 ', 'name' => 'Galón '],
            ['id' => 273, 'code' => 'A77 ', 'name' => 'Unidad De Desplazamiento Cgs Gaussiana '],
            ['id' => 274, 'code' => 'A78 ', 'name' => 'Unidad Gaussiana Cgs De Corriente Eléctrica. '],
            ['id' => 275, 'code' => 'A79 ', 'name' => 'Unidad Gaussian Cgs De Carga Eléctrica. '],
            ['id' => 276, 'code' => 'A8 ', 'name' => 'Amperio Segundo '],
            ['id' => 277, 'code' => 'A80 ', 'name' => 'Unidad Gaussian Cgs De Intensidad De Campo Eléctrico. '],
            ['id' => 278, 'code' => 'A81 ', 'name' => 'Unidad Gaussian Cgs De Polarización Eléctrica. '],
            ['id' => 279, 'code' => 'A82 ', 'name' => 'Unidad Gaussian Cgs De Potencial Eléctrico. '],
            ['id' => 280, 'code' => 'A83 ', 'name' => 'Unidad Gaussiana Cgs De Magnetización. '],
            ['id' => 281, 'code' => 'A84 ', 'name' => 'Gigacoulomb Por Metro Cúbico '],
            ['id' => 282, 'code' => 'A85 ', 'name' => 'Gigaelectronvolt '],
            ['id' => 283, 'code' => 'A86 ', 'name' => 'Gigahercios '],
            ['id' => 284, 'code' => 'A87 ', 'name' => 'Gigaohm '],
            ['id' => 285, 'code' => 'A88 ', 'name' => 'Medidor De Gigaohm '],
            ['id' => 286, 'code' => 'A89 ', 'name' => 'Gigapascal '],
            ['id' => 287, 'code' => 'A9 ', 'name' => 'Tarifa '],
            ['id' => 288, 'code' => 'A90 ', 'name' => 'Gigavatios '],
            ['id' => 289, 'code' => 'A91 ', 'name' => 'Gon '],
            ['id' => 290, 'code' => 'A93 ', 'name' => 'Gramo Por Metro Cúbico '],
            ['id' => 291, 'code' => 'A94 ', 'name' => 'Gramo Por Mol '],
            ['id' => 292, 'code' => 'gris ', 'name' => 'A95 '],
            ['id' => 293, 'code' => 'A96 ', 'name' => 'Gris Por Segundo '],
            ['id' => 294, 'code' => 'A97 ', 'name' => 'Hectopascal '],
            ['id' => 295, 'code' => 'A98 ', 'name' => 'Henry Por Metro '],
            ['id' => 296, 'code' => 'AA ', 'name' => 'Bola '],
            ['id' => 297, 'code' => 'AB ', 'name' => 'Paquete A Granel '],
            ['id' => 298, 'code' => 'ACR ', 'name' => 'Acre '],
            ['id' => 299, 'code' => 'AD ', 'name' => 'Byte '],
            ['id' => 300, 'code' => 'AE ', 'name' => 'Amperio Por Metro '],
            ['id' => 301, 'code' => 'AH ', 'name' => 'Minuto Adicional '],
            ['id' => 302, 'code' => 'AI ', 'name' => 'Minuto Promedio Por Llamada '],
            ['id' => 303, 'code' => 'AJ ', 'name' => 'Policía '],
            ['id' => 304, 'code' => 'AK ', 'name' => 'Braza '],
            ['id' => 305, 'code' => 'AL ', 'name' => '263Nfor De Acceso '],
            ['id' => 306, 'code' => 'AM ', 'name' => 'Ampolla '],
            ['id' => 307, 'code' => 'AMH ', 'name' => 'Hora Amperio '],
            ['id' => 308, 'code' => 'AMP ', 'name' => 'Amperio '],
            ['id' => 309, 'code' => 'ANA ', 'name' => 'Año '],
            ['id' => 310, 'code' => 'AP ', 'name' => 'Solo Libra De Aluminio '],
            ['id' => 311, 'code' => 'APZ ', 'name' => 'Onza Troy O Onza De Boticarios '],
            ['id' => 312, 'code' => 'AQ ', 'name' => 'Unidad De Factor Antihemofílico (Ahf) '],
            ['id' => 313, 'code' => 'AR ', 'name' => 'Supositorio '],
            ['id' => 314, 'code' => 'SON ', 'name' => 'Son '],
            ['id' => 315, 'code' => 'COMO ', 'name' => 'Surtido '],
            ['id' => 316, 'code' => 'ASM ', 'name' => 'Fuerza Alcohólica En Masa '],
            ['id' => 317, 'code' => 'ASU ', 'name' => 'Fuerza Alcohólica Por Volumen '],
            ['id' => 318, 'code' => 'ATM ', 'name' => 'Ambiente Estándar '],
            ['id' => 319, 'code' => 'ATT ', 'name' => 'Ambiente Técnico '],
            ['id' => 320, 'code' => 'AV ', 'name' => 'Cápsula '],
            ['id' => 321, 'code' => 'AW ', 'name' => 'Vial Lleno De Polvo '],
            ['id' => 322, 'code' => 'SÍ ', 'name' => 'Montaje '],
            ['id' => 323, 'code' => 'AZ ', 'name' => 'Unidad Térmica Británica Por Libra '],
            ['id' => 324, 'code' => 'B0 ', 'name' => 'Btu Por Pie Cúbico '],
            ['id' => 325, 'code' => 'B1 ', 'name' => 'Barril (Us) Por Día '],
            ['id' => 326, 'code' => 'B11 ', 'name' => 'Julios Por Kilogramo Kelvin '],
            ['id' => 327, 'code' => 'B12 ', 'name' => 'Julios Por Metro '],
            ['id' => 328, 'code' => 'B13 ', 'name' => 'Julios Por Metro Cuadrado '],
            ['id' => 329, 'code' => 'B14 ', 'name' => 'Julios Por Metro A La Cuarta Potencia '],
            ['id' => 330, 'code' => 'B15 ', 'name' => 'Julios Por Mol '],
            ['id' => 331, 'code' => 'B16 ', 'name' => 'Julios Por Mol Kelvin '],
            ['id' => 332, 'code' => 'B18 ', 'name' => 'Joule Segundo '],
            ['id' => 333, 'code' => 'B2 ', 'name' => 'Litera '],
            ['id' => 334, 'code' => 'B20 ', 'name' => 'Joule Metro Cuadrado Por Kilogramo '],
            ['id' => 335, 'code' => 'B21 ', 'name' => 'Kelvin Por Vatio '],
            ['id' => 336, 'code' => 'B22 ', 'name' => 'Kiloampere '],
            ['id' => 337, 'code' => 'B23 ', 'name' => 'Kiloampere Por Metro Cuadrado '],
            ['id' => 338, 'code' => 'B24 ', 'name' => 'Kiloampere Por Metro '],
            ['id' => 339, 'code' => 'B25 ', 'name' => 'Kilobecquerel Por Kilogramo '],
            ['id' => 340, 'code' => 'B26 ', 'name' => 'Kilocoulomb '],
            ['id' => 341, 'code' => 'B27 ', 'name' => 'Kilocoulomb Por Metro Cúbico '],
            ['id' => 342, 'code' => 'B28 ', 'name' => 'Kilocoulomb Por Metro Cuadrado '],
            ['id' => 343, 'code' => 'B29 ', 'name' => 'Kiloelectronvolt '],
            ['id' => 344, 'code' => 'B3 ', 'name' => 'Libra De Bateo '],
            ['id' => 345, 'code' => 'B31 ', 'name' => 'Kilogramo Metro Por Segundo '],
            ['id' => 346, 'code' => 'B32 ', 'name' => 'Kilogramo Metro Cuadrado '],
            ['id' => 347, 'code' => 'B33 ', 'name' => 'Kilogramo Metro Cuadrado Por Segundo '],
            ['id' => 348, 'code' => 'B34 ', 'name' => 'Kilogramo Por Decímetro Cúbico '],
            ['id' => 349, 'code' => 'B35 ', 'name' => 'Kilogramo Por Litro '],
            ['id' => 350, 'code' => 'B36 ', 'name' => 'Caloría Termoquímica Por Gramo '],
            ['id' => 351, 'code' => 'B37 ', 'name' => 'Kilogramo De Fuerza '],
            ['id' => 352, 'code' => 'B38 ', 'name' => 'Metro De Fuerza De Kilogramo '],
            ['id' => 353, 'code' => 'B39 ', 'name' => 'Metro De Fuerza De Kilogramo Por Segundo '],
            ['id' => 354, 'code' => 'B4 ', 'name' => 'Barril, Imperial '],
            ['id' => 355, 'code' => 'B40 ', 'name' => 'Kilogramo De Fuerza Por Metro Cuadrado '],
            ['id' => 356, 'code' => 'B41 ', 'name' => 'Kilojoule Per Kelvin '],
            ['id' => 357, 'code' => 'B42 ', 'name' => 'Kilojoule Por Kilogramo '],
            ['id' => 358, 'code' => 'B43 ', 'name' => 'Kilojoule Por Kilogramo Kelvin '],
            ['id' => 359, 'code' => 'B44 ', 'name' => 'Kilojoule Por Mol '],
            ['id' => 360, 'code' => 'B45 ', 'name' => 'Kilomol '],
            ['id' => 361, 'code' => 'B46 ', 'name' => 'Kilomol Por Metro Cúbico '],
            ['id' => 362, 'code' => 'B47 ', 'name' => 'Kilonewton '],
            ['id' => 363, 'code' => 'B48 ', 'name' => 'Medidor De Kilonewton '],
            ['id' => 364, 'code' => 'B49 ', 'name' => 'Kiloohm '],
            ['id' => 365, 'code' => 'B5 ', 'name' => 'Palanquilla '],
            ['id' => 366, 'code' => 'B50 ', 'name' => 'Medidor De Kiloohm '],
            ['id' => 367, 'code' => 'B51 ', 'name' => 'Kilopond '],
            ['id' => 368, 'code' => 'B52 ', 'name' => 'Kilosegundo '],
            ['id' => 369, 'code' => 'B53 ', 'name' => 'Kilosiemens '],
            ['id' => 370, 'code' => 'B54 ', 'name' => 'Kilosiemens Por Metro '],
            ['id' => 371, 'code' => 'B55 ', 'name' => 'Kilovoltios Por Metro '],
            ['id' => 372, 'code' => 'B56 ', 'name' => 'Kiloveber Por Metro '],
            ['id' => 373, 'code' => 'B57 ', 'name' => 'Año Luz '],
            ['id' => 374, 'code' => 'B58 ', 'name' => 'Litro Por Mol '],
            ['id' => 375, 'code' => 'B59 ', 'name' => 'Hora Lumen '],
            ['id' => 376, 'code' => 'B6 ', 'name' => 'Bollo '],
            ['id' => 377, 'code' => 'B60 ', 'name' => 'Lumen Por Metro Cuadrado '],
            ['id' => 378, 'code' => 'B61 ', 'name' => 'Lumen Por Vatio '],
            ['id' => 379, 'code' => 'B62 ', 'name' => 'Lumen Segundo '],
            ['id' => 380, 'code' => 'B63 ', 'name' => 'Hora De Lux '],
            ['id' => 381, 'code' => 'B64 ', 'name' => 'Lux Segundo '],
            ['id' => 382, 'code' => 'B65 ', 'name' => 'Maxwell '],
            ['id' => 383, 'code' => 'B66 ', 'name' => 'Megaamperios Por Metro Cuadrado '],
            ['id' => 384, 'code' => 'B67 ', 'name' => 'Megabecquerel Por Kilogramo '],
            ['id' => 385, 'code' => 'B69 ', 'name' => 'Megacoulomb Por Metro Cúbico '],
            ['id' => 386, 'code' => 'B7 ', 'name' => 'Ciclo '],
            ['id' => 387, 'code' => 'B70 ', 'name' => 'Megacoulomb Por Metro Cuadrado '],
            ['id' => 388, 'code' => 'B71 ', 'name' => 'Megaelectronvolt '],
            ['id' => 389, 'code' => 'B72 ', 'name' => 'Megagramo Por Metro Cúbico '],
            ['id' => 390, 'code' => 'B73 ', 'name' => 'Meganewton '],
            ['id' => 391, 'code' => 'B74 ', 'name' => 'Medidor De Meganewton '],
            ['id' => 392, 'code' => 'B75 ', 'name' => 'Megaohm '],
            ['id' => 393, 'code' => 'B76 ', 'name' => 'Metro Megaohm '],
            ['id' => 394, 'code' => 'B77 ', 'name' => 'Megasiemens Por Metro '],
            ['id' => 395, 'code' => 'B78 ', 'name' => 'Megavoltio '],
            ['id' => 396, 'code' => 'B79 ', 'name' => 'Megavolt Por Metro '],
            ['id' => 397, 'code' => 'B8 ', 'name' => 'Julios Por Metro Cúbico '],
            ['id' => 398, 'code' => 'B81 ', 'name' => 'Metro Recíproco Cuadrado Recíproco Segundo '],
            ['id' => 399, 'code' => 'B83 ', 'name' => 'Metro A La Cuarta Potencia '],
            ['id' => 400, 'code' => 'B84 ', 'name' => 'Microamperios '],
            ['id' => 401, 'code' => 'B85 ', 'name' => 'Microbar '],
            ['id' => 402, 'code' => 'B86 ', 'name' => 'Microcoulomb '],
            ['id' => 403, 'code' => 'B87 ', 'name' => 'Microcoulomb Por Metro Cúbico '],
            ['id' => 404, 'code' => 'B88 ', 'name' => 'Microcoulomb Por Metro Cuadrado '],
            ['id' => 405, 'code' => 'B89 ', 'name' => 'Microfarada Por Metro '],
            ['id' => 406, 'code' => 'B9 ', 'name' => 'Batt '],
            ['id' => 407, 'code' => 'B90 ', 'name' => 'Microhenry '],
            ['id' => 408, 'code' => 'B91 ', 'name' => 'Microhenry Por Metro '],
            ['id' => 409, 'code' => 'B92 ', 'name' => 'Micronewton '],
            ['id' => 410, 'code' => 'B93 ', 'name' => 'Medidor De Micronewton '],
            ['id' => 411, 'code' => 'B94 ', 'name' => 'Microohm '],
            ['id' => 412, 'code' => 'B95 ', 'name' => 'Medidor De Microohmios '],
            ['id' => 413, 'code' => 'B96 ', 'name' => 'Micropascal '],
            ['id' => 414, 'code' => 'B97 ', 'name' => 'Microradiano '],
            ['id' => 415, 'code' => 'B98 ', 'name' => 'Microsegundo '],
            ['id' => 416, 'code' => 'B99 ', 'name' => 'Microsiemens '],
            ['id' => 417, 'code' => 'BAR ', 'name' => 'Bar '],
            ['id' => 418, 'code' => 'BB ', 'name' => 'Caja Base '],
            ['id' => 419, 'code' => 'BD ', 'name' => 'Tablero '],
            ['id' => 420, 'code' => 'haz ', 'name' => 'Ser '],
            ['id' => 421, 'code' => 'BFT ', 'name' => 'Pie De Tabla '],
            ['id' => 422, 'code' => 'BG ', 'name' => 'Bolso '],
            ['id' => 423, 'code' => 'BH ', 'name' => 'Cepillo '],
            ['id' => 424, 'code' => 'BHP ', 'name' => 'Potencia Al Freno '],
            ['id' => 425, 'code' => 'BIL ', 'name' => 'Trillón De Dólares '],
            ['id' => 426, 'code' => 'BJ ', 'name' => 'Cangilón '],
            ['id' => 427, 'code' => 'BK ', 'name' => 'Cesta '],
            ['id' => 428, 'code' => 'BL ', 'name' => 'Bala '],
            ['id' => 429, 'code' => 'BLD ', 'name' => 'Barril Seco '],
            ['id' => 430, 'code' => 'BLL ', 'name' => 'Barril (Ee. Uu.) (Petróleo, Etc.) '],
            ['id' => 431, 'code' => 'BO ', 'name' => 'Botella '],
            ['id' => 432, 'code' => 'BP ', 'name' => 'Cien Pies De Tabla '],
            ['id' => 433, 'code' => 'BQL ', 'name' => 'Becquerel '],
            ['id' => 434, 'code' => 'BR ', 'name' => 'Bar '],
            ['id' => 435, 'code' => 'BT ', 'name' => 'Tornillo '],
            ['id' => 436, 'code' => 'C30 ', 'name' => 'Milivoltios Por Metro '],
            ['id' => 437, 'code' => 'C31 ', 'name' => 'Milivatios '],
            ['id' => 438, 'code' => 'C32 ', 'name' => 'Milivatios Por Metro Cuadrado '],
            ['id' => 439, 'code' => 'C33 ', 'name' => 'Milliweber '],
            ['id' => 440, 'code' => 'C34 ', 'name' => 'Topo '],
            ['id' => 441, 'code' => 'C35 ', 'name' => 'Mol Por Decímetro Cúbico '],
            ['id' => 442, 'code' => 'C36 ', 'name' => 'Mol Por Metro Cúbico '],
            ['id' => 443, 'code' => 'C38 ', 'name' => 'Mol Por Litro '],
            ['id' => 444, 'code' => 'C39 ', 'name' => 'Nanoampere '],
            ['id' => 445, 'code' => 'C4 ', 'name' => 'Partido De Carga '],
            ['id' => 446, 'code' => 'C40 ', 'name' => 'Nanocoulomb '],
            ['id' => 447, 'code' => 'C41 ', 'name' => 'Nanofarad '],
            ['id' => 448, 'code' => 'C42 ', 'name' => 'Nanofarad Por Metro '],
            ['id' => 449, 'code' => 'C43 ', 'name' => 'Nanohenry '],
            ['id' => 450, 'code' => 'C44 ', 'name' => 'Nanohenry Por Metro '],
            ['id' => 451, 'code' => 'C45 ', 'name' => 'Nanometro '],
            ['id' => 452, 'code' => 'C46 ', 'name' => 'Medidor De Nanoohm '],
            ['id' => 453, 'code' => 'C47 ', 'name' => 'Nanosegundo '],
            ['id' => 454, 'code' => 'C48 ', 'name' => 'Nanotesla '],
            ['id' => 455, 'code' => 'C49 ', 'name' => 'Nanovatio '],
            ['id' => 456, 'code' => 'C5 ', 'name' => 'Costo '],
            ['id' => 457, 'code' => 'C50 ', 'name' => 'Neper '],
            ['id' => 458, 'code' => 'C51 ', 'name' => 'Neper Por Segundo '],
            ['id' => 459, 'code' => 'C52 ', 'name' => 'Picometro '],
            ['id' => 460, 'code' => 'C53 ', 'name' => 'Metro De Newton Segundo '],
            ['id' => 461, 'code' => 'C54 ', 'name' => 'Newton Metro Cuadrado Kilogramo Cuadrado '],
            ['id' => 462, 'code' => 'C55 ', 'name' => 'Newton Por Metro Cuadrado '],
            ['id' => 463, 'code' => 'C56 ', 'name' => 'Newton Por Milímetro Cuadrado '],
            ['id' => 464, 'code' => 'C57 ', 'name' => 'Newton Segundo '],
            ['id' => 465, 'code' => 'C58 ', 'name' => 'Newton Segundo Por Metro '],
            ['id' => 466, 'code' => 'C59 ', 'name' => 'Octava '],
            ['id' => 467, 'code' => 'C6 ', 'name' => 'Célula '],
            ['id' => 468, 'code' => 'C60 ', 'name' => 'Ohm Centímetro '],
            ['id' => 469, 'code' => 'C61 ', 'name' => 'Ohm Metro '],
            ['id' => 470, 'code' => 'C62 ', 'name' => 'Uno '],
            ['id' => 471, 'code' => 'C63 ', 'name' => 'Parsec '],
            ['id' => 472, 'code' => 'C64 ', 'name' => 'Pascal Por Kelvin '],
            ['id' => 473, 'code' => 'C65 ', 'name' => 'Segundo Pascal '],
            ['id' => 474, 'code' => 'C66 ', 'name' => 'Segundo Pascal Por Metro Cúbico '],
            ['id' => 475, 'code' => 'C67 ', 'name' => 'Segundo Pascal Por Metro '],
            ['id' => 476, 'code' => 'C68 ', 'name' => 'Petajoule '],
            ['id' => 477, 'code' => 'C69 ', 'name' => 'Telefono '],
            ['id' => 478, 'code' => 'C7 ', 'name' => 'Centipoise '],
            ['id' => 479, 'code' => 'C70 ', 'name' => 'Picoampere '],
            ['id' => 480, 'code' => 'C71 ', 'name' => 'Picocoulomb '],
            ['id' => 481, 'code' => 'C72 ', 'name' => 'Picofarad Por Metro '],
            ['id' => 482, 'code' => 'C73 ', 'name' => 'Picohenry '],
            ['id' => 483, 'code' => 'C75 ', 'name' => 'Picowatt '],
            ['id' => 484, 'code' => 'C76 ', 'name' => 'Picowatt Por Metro Cuadrado '],
            ['id' => 485, 'code' => 'C77 ', 'name' => 'Medidor De Libras '],
            ['id' => 486, 'code' => 'C78 ', 'name' => 'Fuerza De Libra '],
            ['id' => 487, 'code' => 'C8 ', 'name' => 'Millicoulomb Por Kilogramo '],
            ['id' => 488, 'code' => 'C80 ', 'name' => 'Rad '],
            ['id' => 489, 'code' => 'C81 ', 'name' => 'Radián '],
            ['id' => 490, 'code' => 'C82 ', 'name' => 'Medidor De Radianes Al Cuadrado Por Mol '],
            ['id' => 491, 'code' => 'C83 ', 'name' => 'Medidor De Radianes Al Cuadrado Por Kilogramo '],
            ['id' => 492, 'code' => 'C84 ', 'name' => 'Radian Por Metro '],
            ['id' => 493, 'code' => 'C85 ', 'name' => 'Â € Ngstr Recíproco “M '],
            ['id' => 494, 'code' => 'C86 ', 'name' => 'Metro Cúbico Recíproco '],
            ['id' => 495, 'code' => 'C87 ', 'name' => 'Metro Cúbico Recíproco Por Segundo '],
            ['id' => 496, 'code' => 'C88 ', 'name' => 'Voltios De Electrones Recíprocos Por Metro Cúbico '],
            ['id' => 497, 'code' => 'C89 ', 'name' => 'Henry Recíproco '],
            ['id' => 498, 'code' => 'C9 ', 'name' => 'Grupo De Bobina '],
            ['id' => 499, 'code' => 'C90 ', 'name' => 'Joule Recíproco Por Metro Cúbico '],
            ['id' => 500, 'code' => 'C91 ', 'name' => 'Kelvin Recíproco O Kelvin Al Poder Menos Uno '],
            ['id' => 501, 'code' => 'C92 ', 'name' => 'Medidor Recíproco '],
            ['id' => 502, 'code' => 'C93 ', 'name' => 'Metro Cuadrado Recíproco '],
            ['id' => 503, 'code' => 'C94 ', 'name' => 'Minuto Recíproco '],
            ['id' => 504, 'code' => 'C95 ', 'name' => 'Mole Recíproco '],
            ['id' => 505, 'code' => 'C96 ', 'name' => 'Pascal Recíproco O Pascal A La Potencia Menos Uno. '],
            ['id' => 506, 'code' => 'C97 ', 'name' => 'Segundo Recíproco '],
            ['id' => 507, 'code' => 'C98 ', 'name' => 'Segundo Recíproco Por Metro Cúbico '],
            ['id' => 508, 'code' => 'C99 ', 'name' => 'Segundo Recíproco Por Metro Cuadrado '],
            ['id' => 509, 'code' => 'CA ', 'name' => 'Caja '],
            ['id' => 510, 'code' => 'CCT ', 'name' => 'Capacidad De Carga En Toneladas Métricas. '],
            ['id' => 511, 'code' => 'CDL ', 'name' => 'Candela '],
            ['id' => 512, 'code' => 'CEL ', 'name' => 'Grado Celsius '],
            ['id' => 513, 'code' => 'CEN ', 'name' => 'Cien '],
            ['id' => 514, 'code' => 'CG ', 'name' => 'Tarjeta '],
            ['id' => 515, 'code' => 'CGM ', 'name' => 'Centigramo '],
            ['id' => 516, 'code' => 'CH ', 'name' => 'Envase '],
            ['id' => 517, 'code' => 'CJ ', 'name' => 'Cono '],
            ['id' => 518, 'code' => 'CK ', 'name' => 'Conector '],
            ['id' => 519, 'code' => 'CKG ', 'name' => 'Coulomb Por Kilogramo '],
            ['id' => 520, 'code' => 'CL ', 'name' => 'Bobina '],
            ['id' => 521, 'code' => 'CLF ', 'name' => 'Cientos De Licencia '],
            ['id' => 522, 'code' => 'CLT ', 'name' => 'Centilitro '],
            ['id' => 523, 'code' => 'CMK ', 'name' => 'Centímetro Cuadrado '],
            ['id' => 524, 'code' => 'CMQ ', 'name' => 'Centímetro Cúbico '],
            ['id' => 525, 'code' => 'CMT ', 'name' => 'Centímetro '],
            ['id' => 526, 'code' => 'CNP ', 'name' => 'Paquete De Cien '],
            ['id' => 527, 'code' => 'CNT ', 'name' => 'Cental (Reino Unido) '],
            ['id' => 528, 'code' => 'CO ', 'name' => 'Garrafón '],
            ['id' => 529, 'code' => 'COU ', 'name' => 'Culombio '],
            ['id' => 530, 'code' => 'CQ ', 'name' => 'Cartucho '],
            ['id' => 531, 'code' => 'CR ', 'name' => 'Caja '],
            ['id' => 532, 'code' => 'CS ', 'name' => 'Caso '],
            ['id' => 533, 'code' => 'CT ', 'name' => 'Caja De Cartón '],
            ['id' => 534, 'code' => 'CTM ', 'name' => 'Quilate Métrico '],
            ['id' => 535, 'code' => 'CU ', 'name' => 'Vaso '],
            ['id' => 536, 'code' => 'CUR ', 'name' => 'Curie '],
            ['id' => 537, 'code' => 'CV ', 'name' => 'Cubrir '],
            ['id' => 538, 'code' => 'CWA ', 'name' => 'Cien Libras (Quintales) / Cien Pesos (Us) '],
            ['id' => 539, 'code' => 'CWI ', 'name' => 'Cien Pesos (Reino Unido) '],
            ['id' => 540, 'code' => 'CY ', 'name' => 'Cilindro '],
            ['id' => 541, 'code' => 'CZ ', 'name' => 'Combo '],
            ['id' => 542, 'code' => 'D1 ', 'name' => 'Segundo Recíproco Por Esteradiano '],
            ['id' => 543, 'code' => 'D10 ', 'name' => 'Siemens Por Metro '],
            ['id' => 544, 'code' => 'D12 ', 'name' => 'Siemens Metro Cuadrado Por Mol '],
            ['id' => 545, 'code' => 'D13 ', 'name' => 'Sievert '],
            ['id' => 546, 'code' => 'D14 ', 'name' => 'Mil Yardas Lineales '],
            ['id' => 547, 'code' => 'D15 ', 'name' => 'Sone '],
            ['id' => 548, 'code' => 'D16 ', 'name' => 'Centímetro Cuadrado Por Ergio '],
            ['id' => 549, 'code' => 'D17 ', 'name' => 'Centímetro Cuadrado Por Erg Esterlina '],
            ['id' => 550, 'code' => 'D18 ', 'name' => 'Metro Kelvin '],
            ['id' => 551, 'code' => 'D19 ', 'name' => 'Kelvin Metro Cuadrado Por Vatio '],
            ['id' => 552, 'code' => 'D2 ', 'name' => 'Segundo Recíproco Por Metros Cuadrados Esteradianos '],
            ['id' => 553, 'code' => 'D20 ', 'name' => 'Metro Cuadrado Por Julio '],
            ['id' => 554, 'code' => 'D21 ', 'name' => 'Metro Cuadrado Por Kilogramo '],
            ['id' => 555, 'code' => 'D22 ', 'name' => 'Metro Cuadrado Por Mol '],
            ['id' => 556, 'code' => 'D23 ', 'name' => 'Pluma Gramo (Proteína) '],
            ['id' => 557, 'code' => 'D24 ', 'name' => 'Metro Cuadrado Por Esterilizador '],
            ['id' => 558, 'code' => 'D25 ', 'name' => 'Metro Cuadrado Por Julios Esteradianos '],
            ['id' => 559, 'code' => 'D26 ', 'name' => 'Metro Cuadrado Por Voltio Segundo '],
            ['id' => 560, 'code' => 'D27 ', 'name' => 'Esteradiano '],
            ['id' => 561, 'code' => 'D28 ', 'name' => 'Sifón '],
            ['id' => 562, 'code' => 'D29 ', 'name' => 'Terahercios '],
            ['id' => 563, 'code' => 'D30 ', 'name' => 'Terajulio '],
            ['id' => 564, 'code' => 'D31 ', 'name' => 'Teravatio '],
            ['id' => 565, 'code' => 'D32 ', 'name' => 'Hora De Teravatio '],
            ['id' => 566, 'code' => 'D33 ', 'name' => 'Tesla '],
            ['id' => 567, 'code' => 'D34 ', 'name' => 'Texas '],
            ['id' => 568, 'code' => 'D35 ', 'name' => 'Caloría Termoquímica '],
            ['id' => 569, 'code' => 'D37 ', 'name' => 'Caloría Termoquímica Por Gramo Kelvin '],
            ['id' => 570, 'code' => 'D38 ', 'name' => 'Calorías Termoquímicas Por Segundo Centímetro Kelvin '],
            ['id' => 571, 'code' => 'D39 ', 'name' => 'Calorías Termoquímicas Por Segundo Centímetro Cuadrado Kelvin '],
            ['id' => 572, 'code' => 'D40 ', 'name' => 'Mil Litros '],
            ['id' => 573, 'code' => 'D41 ', 'name' => 'Tonelada Por Metro Cúbico '],
            ['id' => 574, 'code' => 'D42 ', 'name' => 'Año Tropical '],
            ['id' => 575, 'code' => 'D43 ', 'name' => 'Unidad De Masa Atómica Unificada '],
            ['id' => 576, 'code' => 'D44 ', 'name' => 'Var '],
            ['id' => 577, 'code' => 'D45 ', 'name' => 'Voltios Al Cuadrado Por Kelvin Al Cuadrado '],
            ['id' => 578, 'code' => 'D46 ', 'name' => 'Voltio – Amperio '],
            ['id' => 579, 'code' => 'D47 ', 'name' => 'Voltio Por Centímetro '],
            ['id' => 580, 'code' => 'D48 ', 'name' => 'Voltio Por Kelvin '],
            ['id' => 581, 'code' => 'D49 ', 'name' => 'Milivoltios Por Kelvin '],
            ['id' => 582, 'code' => 'D5 ', 'name' => 'Kilogramo Por Centímetro Cuadrado '],
            ['id' => 583, 'code' => 'D50 ', 'name' => 'Voltios Por Metro '],
            ['id' => 584, 'code' => 'D51 ', 'name' => 'Voltios Por Milímetro '],
            ['id' => 585, 'code' => 'D52 ', 'name' => 'Vatios Por Kelvin '],
            ['id' => 586, 'code' => 'D53 ', 'name' => 'Vatios Por Metro Kelvin '],
            ['id' => 587, 'code' => 'D54 ', 'name' => 'Vatios Por Metro Cuadrado '],
            ['id' => 588, 'code' => 'D55 ', 'name' => 'Vatios Por Metro Cuadrado Kelvin '],
            ['id' => 589, 'code' => 'D56 ', 'name' => 'Vatios Por Metro Cuadrado De Kelvin A La Cuarta Potencia '],
            ['id' => 590, 'code' => 'D57 ', 'name' => 'Vatios Por Steradian '],
            ['id' => 591, 'code' => 'D58 ', 'name' => 'Vatios Por Metro Cuadrado Esterlino '],
            ['id' => 592, 'code' => 'D59 ', 'name' => 'Weber Por Metro '],
            ['id' => 593, 'code' => 'D6 ', 'name' => 'Röntgen Por Segundo '],
            ['id' => 594, 'code' => 'D60 ', 'name' => 'Weber Por Milímetro '],
            ['id' => 595, 'code' => 'D61 ', 'name' => 'Minuto '],
            ['id' => 596, 'code' => 'D62 ', 'name' => 'Segundo '],
            ['id' => 597, 'code' => 'D63 ', 'name' => 'Libro '],
            ['id' => 598, 'code' => 'D64 ', 'name' => 'Bloquear '],
            ['id' => 599, 'code' => 'D65 ', 'name' => 'Redondo '],
            ['id' => 600, 'code' => 'D66 ', 'name' => 'Casete '],
            ['id' => 601, 'code' => 'D67 ', 'name' => 'Dólar Por Hora '],
            ['id' => 602, 'code' => 'D69 ', 'name' => 'Pulgada A La Cuarta Potencia '],
            ['id' => 603, 'code' => 'D7 ', 'name' => 'Sandwich '],
            ['id' => 604, 'code' => 'D70 ', 'name' => 'Tabla Internacional (It) Caloría '],
            ['id' => 605, 'code' => 'D71 ', 'name' => 'Tabla Internacional (It) Calorías Por Segundo Centímetro Kelvin '],
            ['id' => 606, 'code' => 'D72 ', 'name' => 'Tabla Internacional (It) Calorías Por Segundo Centímetro Cuadrado Kelvin '],
            ['id' => 607, 'code' => 'D73 ', 'name' => 'Joule Metro Cuadrado '],
            ['id' => 608, 'code' => 'D74 ', 'name' => 'Kilogramo Por Mol '],
            ['id' => 609, 'code' => 'D75 ', 'name' => 'Tabla Internacional (It) Calorías Por Gramo '],
            ['id' => 610, 'code' => 'D76 ', 'name' => 'Tabla Internacional (It) Calorías Por Gramo Kelvin '],
            ['id' => 611, 'code' => 'D77 ', 'name' => 'Megacoulomb '],
            ['id' => 612, 'code' => 'D79 ', 'name' => 'Haz '],
            ['id' => 613, 'code' => 'D8 ', 'name' => 'Puntaje De Drenaje '],
            ['id' => 614, 'code' => 'D80 ', 'name' => 'Microwatt '],
            ['id' => 615, 'code' => 'D81 ', 'name' => 'Microtesla '],
            ['id' => 616, 'code' => 'D82 ', 'name' => 'Microvoltio '],
            ['id' => 617, 'code' => 'D83 ', 'name' => 'Medidor De Millinewton '],
            ['id' => 618, 'code' => 'D85 ', 'name' => 'Microwatt Por Metro Cuadrado '],
            ['id' => 619, 'code' => 'D86 ', 'name' => 'Millicoulomb '],
            ['id' => 620, 'code' => 'D87 ', 'name' => 'Milimol Por Kilogramo '],
            ['id' => 621, 'code' => 'D88 ', 'name' => 'Millicoulomb Por Metro Cúbico '],
            ['id' => 622, 'code' => 'D89 ', 'name' => 'Millicoulomb Por Metro Cuadrado '],
            ['id' => 623, 'code' => 'D9 ', 'name' => 'Dina Por Centímetro Cuadrado '],
            ['id' => 624, 'code' => 'D90 ', 'name' => 'Metro Cúbico (Neto) '],
            ['id' => 625, 'code' => 'D91 ', 'name' => 'Movimiento Rápido Del Ojo '],
            ['id' => 626, 'code' => 'D92 ', 'name' => 'Banda '],
            ['id' => 627, 'code' => 'D93 ', 'name' => 'Segundo Por Metro Cúbico '],
            ['id' => 628, 'code' => 'D94 ', 'name' => 'Segundo Por Metro Cúbico Radianes '],
            ['id' => 629, 'code' => 'D95 ', 'name' => 'Julios Por Gramo '],
            ['id' => 630, 'code' => 'D96 ', 'name' => 'Libra Bruta '],
            ['id' => 631, 'code' => 'D97 ', 'name' => 'Carga De Palet / Unidad '],
            ['id' => 632, 'code' => 'D98 ', 'name' => 'Libra De Masa '],
            ['id' => 633, 'code' => 'D99 ', 'name' => 'Manga '],
            ['id' => 634, 'code' => 'DAA ', 'name' => 'Despreciar '],
            ['id' => 635, 'code' => 'DAD ', 'name' => 'Diez Dias '],
            ['id' => 636, 'code' => 'día ', 'name' => 'Day '],
            ['id' => 637, 'code' => 'DB ', 'name' => 'Libra Seca '],
            ['id' => 638, 'code' => 'DC ', 'name' => 'Disco '],
            ['id' => 639, 'code' => 'DD ', 'name' => 'La Licenciatura '],
            ['id' => 640, 'code' => 'DE ', 'name' => 'Acuerdo '],
            ['id' => 641, 'code' => 'DEC ', 'name' => 'Década '],
            ['id' => 642, 'code' => 'DG ', 'name' => 'Decigramo '],
            ['id' => 643, 'code' => 'DI ', 'name' => 'Dispensador '],
            ['id' => 644, 'code' => 'DJ ', 'name' => 'Decagramo '],
            ['id' => 645, 'code' => 'DLT ', 'name' => 'Decilitro '],
            ['id' => 646, 'code' => 'DMK ', 'name' => '263Nformaci Cuadrado '],
            ['id' => 647, 'code' => 'DMQ ', 'name' => 'Decímetro Cúbico '],
            ['id' => 648, 'code' => 'DMT ', 'name' => 'Decímetro '],
            ['id' => 649, 'code' => 'DN ', 'name' => 'Medidor De Decinewton '],
            ['id' => 650, 'code' => 'DPC ', 'name' => 'Docena Pieza '],
            ['id' => 651, 'code' => 'DPR ', 'name' => 'Docena Par '],
            ['id' => 652, 'code' => 'DPT ', 'name' => 'Tonelaje De Desplazamiento '],
            ['id' => 653, 'code' => 'DQ ', 'name' => 'Registro De Datos '],
            ['id' => 654, 'code' => 'DR ', 'name' => 'Tambor '],
            ['id' => 655, 'code' => 'DRA ', 'name' => 'Dram (Us) '],
            ['id' => 656, 'code' => 'DRI ', 'name' => 'Dram (Reino Unido) '],
            ['id' => 657, 'code' => 'DRL ', 'name' => 'Docena Rollo '],
            ['id' => 658, 'code' => 'DRM ', 'name' => 'Dracma (Reino Unido) '],
            ['id' => 659, 'code' => 'DS ', 'name' => 'Monitor '],
            ['id' => 660, 'code' => 'DT ', 'name' => 'Tonelada Seca '],
            ['id' => 661, 'code' => 'DTN ', 'name' => 'Decitonne '],
            ['id' => 662, 'code' => 'DU ', 'name' => 'Dina '],
            ['id' => 663, 'code' => 'DWT ', 'name' => 'Pennyweight '],
            ['id' => 664, 'code' => 'DX ', 'name' => 'Dina Por Centímetro '],
            ['id' => 665, 'code' => 'DY ', 'name' => 'Libro De Directorio '],
            ['id' => 666, 'code' => 'DZN ', 'name' => 'Docena '],
            ['id' => 667, 'code' => 'DZP ', 'name' => 'Paquete De Doce '],
            ['id' => 668, 'code' => 'E2 ', 'name' => 'Cinturón '],
            ['id' => 669, 'code' => 'E3 ', 'name' => 'Remolque '],
            ['id' => 670, 'code' => 'E4 ', 'name' => 'Kilogramo Bruto '],
            ['id' => 671, 'code' => 'E5 ', 'name' => 'Tonelada Métrica Larga '],
            ['id' => 672, 'code' => 'EA ', 'name' => 'Cada '],
            ['id' => 673, 'code' => 'EB ', 'name' => 'Casilla De Correo Electrónico '],
            ['id' => 674, 'code' => 'CE ', 'name' => 'Cada Uno Por Mes '],
            ['id' => 675, 'code' => 'EP ', 'name' => 'Paquete De Once '],
            ['id' => 676, 'code' => 'EQ ', 'name' => 'Galón Equivalente '],
            ['id' => 677, 'code' => 'EV ', 'name' => 'Sobre '],
            ['id' => 678, 'code' => 'F1 ', 'name' => 'Mil Pies Cúbicos Por Día '],
            ['id' => 679, 'code' => 'F9 ', 'name' => 'Fibra Por Centímetro Cúbico De Aire '],
            ['id' => 680, 'code' => 'FAH ', 'name' => 'Grado Fahrenheit '],
            ['id' => 681, 'code' => 'FAR ', 'name' => 'Faradio '],
            ['id' => 682, 'code' => 'FB ', 'name' => 'Campo '],
            ['id' => 683, 'code' => 'FC ', 'name' => 'Mil Pies Cúbicos '],
            ['id' => 684, 'code' => 'FD ', 'name' => 'Millón De Partículas Por Pie Cúbico '],
            ['id' => 685, 'code' => 'FE ', 'name' => 'Pie De Pista '],
            ['id' => 686, 'code' => 'FF ', 'name' => 'Cien Metros Cúbicos '],
            ['id' => 687, 'code' => 'FG ', 'name' => 'Parche Transdérmico '],
            ['id' => 688, 'code' => 'FH ', 'name' => 'Micromol '],
            ['id' => 689, 'code' => 'FL ', 'name' => 'Tonelada En Escamas '],
            ['id' => 690, 'code' => 'FM ', 'name' => 'Millones De Pies Cúbicos '],
            ['id' => 691, 'code' => 'pie ', 'name' => 'Fot '],
            ['id' => 692, 'code' => 'FP ', 'name' => 'Libra Por Pie Cuadrado '],
            ['id' => 693, 'code' => 'FR ', 'name' => 'Pie Por Minuto '],
            ['id' => 694, 'code' => 'FS ', 'name' => 'Pie Por Segundo '],
            ['id' => 695, 'code' => 'FTK ', 'name' => 'Pie Cuadrado '],
            ['id' => 696, 'code' => 'FTQ ', 'name' => 'Pie Cubico '],
            ['id' => 697, 'code' => 'G2 ', 'name' => 'Us Galones Por Minuto '],
            ['id' => 698, 'code' => 'G3 ', 'name' => 'Galon Imperial Por Minuto '],
            ['id' => 699, 'code' => 'G7 ', 'name' => 'Hoja De Microficha '],
            ['id' => 700, 'code' => 'GB ', 'name' => 'Galón (Us) Por Día '],
            ['id' => 701, 'code' => 'GBQ ', 'name' => 'Gigabecquerel '],
            ['id' => 702, 'code' => 'GC ', 'name' => 'Gramo Por 100 Gramo '],
            ['id' => 703, 'code' => 'GD ', 'name' => 'Barril Bruto '],
            ['id' => 704, 'code' => 'GE ', 'name' => 'Libra Por Galón (Us) '],
            ['id' => 705, 'code' => 'GF ', 'name' => 'Gramo Por Metro (Gramo Por 100 Centímetros) '],
            ['id' => 706, 'code' => 'GFI ', 'name' => 'Gramo De Isótopo Fisionable '],
            ['id' => 707, 'code' => 'GGR ', 'name' => 'Gramo '],
            ['id' => 708, 'code' => 'GH ', 'name' => 'Medio Galón (Ee. Uu.) '],
            ['id' => 709, 'code' => 'GIA ', 'name' => 'Branquias '],
            ['id' => 710, 'code' => 'GII ', 'name' => 'Gill (Reino Unido) '],
            ['id' => 711, 'code' => 'GJ ', 'name' => 'Gramo Por Mililitro '],
            ['id' => 712, 'code' => 'GL ', 'name' => 'Gramo Por Litro '],
            ['id' => 713, 'code' => 'GLD ', 'name' => 'Galón Seco (Ee. Uu.) '],
            ['id' => 714, 'code' => 'GLI ', 'name' => 'Galón (Reino Unido) '],
            ['id' => 715, 'code' => 'GLL ', 'name' => 'Galón '],
            ['id' => 716, 'code' => 'GM ', 'name' => 'Gramo Por Metro Cuadrado '],
            ['id' => 717, 'code' => 'GN ', 'name' => 'Galón Bruto '],
            ['id' => 718, 'code' => 'GO ', 'name' => 'Miligramos Por Metro Cuadrado '],
            ['id' => 719, 'code' => 'GP ', 'name' => 'Miligramo Por Metro Cúbico '],
            ['id' => 720, 'code' => 'GQ ', 'name' => 'Microgramos Por Metro Cúbico '],
            ['id' => 721, 'code' => 'GRM ', 'name' => 'Gramo '],
            ['id' => 722, 'code' => 'GRN ', 'name' => 'Grano '],
            ['id' => 723, 'code' => 'GRO ', 'name' => 'Bruto '],
            ['id' => 724, 'code' => 'GRT ', 'name' => 'Tonelada De Registro Bruto '],
            ['id' => 725, 'code' => 'GT ', 'name' => 'Tonelada Bruta '],
            ['id' => 726, 'code' => 'GV ', 'name' => 'Gigajoule '],
            ['id' => 727, 'code' => 'GW ', 'name' => 'Galón Por Mil Pies Cúbicos '],
            ['id' => 728, 'code' => 'GWH ', 'name' => 'Hora De Gigavatios '],
            ['id' => 729, 'code' => 'GY ', 'name' => 'Patio Bruto '],
            ['id' => 730, 'code' => 'GZ ', 'name' => 'Sistema De Medición '],
            ['id' => 731, 'code' => 'H1 ', 'name' => 'Media Página – Electrónica '],
            ['id' => 732, 'code' => 'H2 ', 'name' => 'Medio Litro '],
            ['id' => 733, 'code' => 'HA ', 'name' => 'Madeja '],
            ['id' => 734, 'code' => 'HAR ', 'name' => 'Hectárea '],
            ['id' => 735, 'code' => 'HBA ', 'name' => 'Hectobar '],
            ['id' => 736, 'code' => 'HBX ', 'name' => 'Cien Cajas '],
            ['id' => 737, 'code' => 'HC ', 'name' => 'Cien Cuentas '],
            ['id' => 738, 'code' => 'HD ', 'name' => 'Media Docena '],
            ['id' => 739, 'code' => 'ÉL ', 'name' => 'Centésima De Quilate '],
            ['id' => 740, 'code' => 'HF ', 'name' => 'Cien Pies '],
            ['id' => 741, 'code' => 'HGM ', 'name' => 'Hectogramo '],
            ['id' => 742, 'code' => 'HH ', 'name' => 'Cien Pies Cúbicos '],
            ['id' => 743, 'code' => 'HI ', 'name' => 'Cien Hojas '],
            ['id' => 744, 'code' => 'HIU ', 'name' => 'Cien Unidades Internacionales '],
            ['id' => 745, 'code' => 'HJ ', 'name' => 'Caballo Métrico '],
            ['id' => 746, 'code' => 'HK ', 'name' => 'Cien Kilogramos '],
            ['id' => 747, 'code' => 'HL ', 'name' => 'Cien Pies (Lineales) '],
            ['id' => 748, 'code' => 'HLT ', 'name' => 'Hectolitro '],
            ['id' => 749, 'code' => 'HM ', 'name' => 'Milla Por Hora '],
            ['id' => 750, 'code' => 'HMQ ', 'name' => 'Millones De Metros Cúbicos '],
            ['id' => 751, 'code' => 'HMT ', 'name' => 'Hectómetro '],
            ['id' => 752, 'code' => 'HN ', 'name' => 'Milímetro Convencional De Mercurio '],
            ['id' => 753, 'code' => 'HO ', 'name' => 'Cien Onzas Troy '],
            ['id' => 754, 'code' => 'HP ', 'name' => 'Milímetro Convencional De Agua '],
            ['id' => 755, 'code' => 'HPA ', 'name' => 'Hectolitro De Alcohol Puro '],
            ['id' => 756, 'code' => 'HS ', 'name' => 'Cien Pies Cuadrados '],
            ['id' => 757, 'code' => 'HT ', 'name' => 'Media Hora '],
            ['id' => 758, 'code' => 'HTZ ', 'name' => 'Hertz '],
            ['id' => 759, 'code' => 'HUR ', 'name' => 'Hora '],
            ['id' => 760, 'code' => 'HY ', 'name' => 'Cien Yardas '],
            ['id' => 761, 'code' => 'IA ', 'name' => 'Pulgada Libra '],
            ['id' => 762, 'code' => 'IC ', 'name' => 'Contar Por Pulgada '],
            ['id' => 763, 'code' => 'IE ', 'name' => 'Persona '],
            ['id' => 764, 'code' => 'IF ', 'name' => 'Pulgadas De Agua '],
            ['id' => 765, 'code' => 'II ', 'name' => 'Columna Pulgada '],
            ['id' => 766, 'code' => 'IL ', 'name' => 'Pulgada Por Minuto '],
            ['id' => 767, 'code' => 'IM ', 'name' => 'Impresión '],
            ['id' => 768, 'code' => 'INH ', 'name' => 'Pulgada '],
            ['id' => 769, 'code' => 'KI ', 'name' => 'Kilogramo Por Milímetro De Ancho '],
            ['id' => 770, 'code' => 'KJ ', 'name' => 'Kilosegmento '],
            ['id' => 771, 'code' => 'KJO ', 'name' => 'Kilojoule '],
            ['id' => 772, 'code' => 'KL ', 'name' => 'Kilogramo Por Metro '],
            ['id' => 773, 'code' => 'KMH ', 'name' => 'Kilómetro Por Hora '],
            ['id' => 774, 'code' => 'KMK ', 'name' => 'Kilometro Cuadrado '],
            ['id' => 775, 'code' => 'KMQ ', 'name' => 'Kilogramo Por Metro Cúbico '],
            ['id' => 776, 'code' => 'KNI ', 'name' => 'Kilogramo De Nitrógeno '],
            ['id' => 777, 'code' => 'KNS ', 'name' => 'Kilogramo De Sustancia Nombrada '],
            ['id' => 778, 'code' => 'nudo ', 'name' => 'Knt '],
            ['id' => 779, 'code' => 'KO ', 'name' => 'Milliequivalencia De Potasa Cáustica Por Gramo De Producto. '],
            ['id' => 780, 'code' => 'KPA ', 'name' => 'Kilopascal '],
            ['id' => 781, 'code' => 'KPH ', 'name' => 'Kilogramo De Hidróxido De Potasio (Potasa Cáustica) '],
            ['id' => 782, 'code' => 'KPO ', 'name' => 'Kilogramo De Óxido De Potasio '],
            ['id' => 783, 'code' => 'KPP ', 'name' => 'Kilogramo De Pentóxido De Fósforo (Anhídrido Fosfórico) '],
            ['id' => 784, 'code' => 'KR ', 'name' => 'Kilorã¶Ntgen '],
            ['id' => 785, 'code' => 'KS ', 'name' => 'Mil Libras Por Pulgada Cuadrada '],
            ['id' => 786, 'code' => 'KSD ', 'name' => 'Kilogramo De Sustancia 90% Seca '],
            ['id' => 787, 'code' => 'KSH ', 'name' => 'Kilogramo De Hidróxido De Sodio (Soda Cáustica) '],
            ['id' => 788, 'code' => 'KT ', 'name' => 'Equipo '],
            ['id' => 789, 'code' => 'KTM ', 'name' => 'Kilómetro '],
            ['id' => 790, 'code' => 'KTN ', 'name' => 'Kilotonne '],
            ['id' => 791, 'code' => 'KUR ', 'name' => 'Kilogramo De Uranio '],
            ['id' => 792, 'code' => 'KVA ', 'name' => 'Kilovoltio – Ampere '],
            ['id' => 793, 'code' => 'KVR ', 'name' => 'Kilovar '],
            ['id' => 794, 'code' => 'KVT ', 'name' => 'Kilovoltio '],
            ['id' => 795, 'code' => 'KW ', 'name' => 'Kilogramos Por Milímetro '],
            ['id' => 796, 'code' => 'KWH ', 'name' => 'Kilovatios Hora '],
            ['id' => 797, 'code' => 'KWT ', 'name' => 'Kilovatio '],
            ['id' => 798, 'code' => 'KX ', 'name' => 'Mililitro Por Kilogramo '],
            ['id' => 799, 'code' => 'L2 ', 'name' => 'Litro Por Minuto '],
            ['id' => 800, 'code' => 'LA ', 'name' => 'Libra Por Pulgada Cúbica '],
            ['id' => 801, 'code' => 'LBR ', 'name' => 'Libra '],
            ['id' => 802, 'code' => 'LBT ', 'name' => 'Libra Troy '],
            ['id' => 803, 'code' => 'LC ', 'name' => 'Centímetro Lineal '],
            ['id' => 804, 'code' => 'LD ', 'name' => 'Litro Por Día '],
            ['id' => 805, 'code' => 'LE ', 'name' => 'Lite '],
            ['id' => 806, 'code' => 'LEF ', 'name' => 'Hoja '],
            ['id' => 807, 'code' => 'LF ', 'name' => 'Pie Lineal '],
            ['id' => 808, 'code' => 'LH ', 'name' => 'Hora De Trabajo '],
            ['id' => 809, 'code' => 'LI ', 'name' => 'Pulgada Lineal '],
            ['id' => 810, 'code' => 'LJ ', 'name' => 'Spray Grande '],
            ['id' => 811, 'code' => 'LK ', 'name' => 'Enlazar '],
            ['id' => 812, 'code' => 'LM ', 'name' => 'Metro Lineal '],
            ['id' => 813, 'code' => 'LN ', 'name' => 'Longitud '],
            ['id' => 814, 'code' => 'LO ', 'name' => 'Mucho '],
            ['id' => 815, 'code' => 'LP ', 'name' => 'Libra Liquida '],
            ['id' => 816, 'code' => 'LPA ', 'name' => 'Litro De Alcohol Puro '],
            ['id' => 817, 'code' => 'LR ', 'name' => 'Capa '],
            ['id' => 818, 'code' => 'LS ', 'name' => 'Suma Global '],
            ['id' => 819, 'code' => 'LTN ', 'name' => 'Ton (Reino Unido) O Longton (Ee. Uu.) '],
            ['id' => 820, 'code' => 'LTR ', 'name' => 'Litro '],
            ['id' => 821, 'code' => 'LUM ', 'name' => 'Lumen '],
            ['id' => 822, 'code' => 'lux ', 'name' => 'Lux '],
            ['id' => 823, 'code' => 'LX ', 'name' => 'Yarda Lineal Por Libra '],
            ['id' => 824, 'code' => 'LY ', 'name' => 'Yarda Lineal '],
            ['id' => 825, 'code' => 'M0 ', 'name' => 'Cinta Magnética '],
            ['id' => 826, 'code' => 'M1 ', 'name' => 'Miligramos Por Litro '],
            ['id' => 827, 'code' => 'M4 ', 'name' => 'Valor Monetario '],
            ['id' => 828, 'code' => 'M5 ', 'name' => 'Microcurie '],
            ['id' => 829, 'code' => 'M7 ', 'name' => 'Micropulgada '],
            ['id' => 830, 'code' => 'M9 ', 'name' => 'Millones De Btu Por 1000 Pies Cúbicos '],
            ['id' => 831, 'code' => 'MA ', 'name' => 'Máquina Por Unidad '],
            ['id' => 832, 'code' => 'MAL ', 'name' => 'Mega Litro '],
            ['id' => 833, 'code' => 'MAM ', 'name' => 'Megametro '],
            ['id' => 834, 'code' => 'MAW ', 'name' => 'Megavatio '],
            ['id' => 835, 'code' => 'MBE ', 'name' => 'Mil Equivalentes De Ladrillo Estándar '],
            ['id' => 836, 'code' => 'MBF ', 'name' => 'Mil Pies De Tabla '],
            ['id' => 837, 'code' => 'MBR ', 'name' => 'Milibar '],
            ['id' => 838, 'code' => 'MC ', 'name' => 'Microgramo '],
            ['id' => 839, 'code' => 'MCU ', 'name' => 'Milicurie '],
            ['id' => 840, 'code' => 'MD ', 'name' => 'Aire Seco Tonelada Métrica '],
            ['id' => 841, 'code' => 'MF ', 'name' => 'Miligramo Por Pie Cuadrado Por Lado '],
            ['id' => 842, 'code' => 'MGM ', 'name' => 'Miligramo '],
            ['id' => 843, 'code' => 'MIK ', 'name' => 'Milla Cuadrada '],
            ['id' => 844, 'code' => 'mil ', 'name' => 'Mil '],
            ['id' => 845, 'code' => 'MIN ', 'name' => 'Minuto '],
            ['id' => 846, 'code' => 'MIO ', 'name' => 'Millón '],
            ['id' => 847, 'code' => 'MIU ', 'name' => 'Millones De Unidades Internacionales '],
            ['id' => 848, 'code' => 'MK ', 'name' => 'Miligramo Por Pulgada Cuadrada '],
            ['id' => 849, 'code' => 'MLD ', 'name' => 'Mil Millones '],
            ['id' => 850, 'code' => 'MLT ', 'name' => 'Mililitro '],
            ['id' => 851, 'code' => 'MMK ', 'name' => 'Milímetro Cuadrado '],
            ['id' => 852, 'code' => 'MMQ ', 'name' => 'Milímetro Cúbico '],
            ['id' => 853, 'code' => 'MMT ', 'name' => 'Milímetro '],
            ['id' => 854, 'code' => 'LUN ', 'name' => 'Mes '],
            ['id' => 855, 'code' => 'MPA ', 'name' => 'Megapascal '],
            ['id' => 856, 'code' => 'MQ ', 'name' => 'Mil Metros '],
            ['id' => 857, 'code' => 'MQH ', 'name' => 'Metro Cúbico Por Hora '],
            ['id' => 858, 'code' => 'MQS ', 'name' => 'Metro Cúbico Por Segundo '],
            ['id' => 859, 'code' => 'MSK ', 'name' => 'Metro Por Segundo Al Cuadrado '],
            ['id' => 860, 'code' => 'MT ', 'name' => 'Estera '],
            ['id' => 861, 'code' => 'MTK ', 'name' => 'Metro Cuadrado '],
            ['id' => 862, 'code' => 'MTQ ', 'name' => 'Metro Cúbico '],
            ['id' => 863, 'code' => 'MTR ', 'name' => 'Metro '],
            ['id' => 864, 'code' => 'MTS ', 'name' => 'Metro Por Segundo '],
            ['id' => 865, 'code' => 'MV ', 'name' => 'Numero De Mults '],
            ['id' => 866, 'code' => 'MVA ', 'name' => 'Megavolt – Ampere '],
            ['id' => 867, 'code' => 'MWH ', 'name' => 'Megavatios Hora (1000 Kw.H) '],
            ['id' => 868, 'code' => 'N1 ', 'name' => 'Calorías De La Pluma '],
            ['id' => 869, 'code' => 'N2 ', 'name' => 'Número De Líneas '],
            ['id' => 870, 'code' => 'N3 ', 'name' => 'Punto De Impresión '],
            ['id' => 871, 'code' => 'NA ', 'name' => 'Miligramo Por Kilogramo '],
            ['id' => 872, 'code' => 'NAR ', 'name' => 'Número De Artículos '],
            ['id' => 873, 'code' => 'NB ', 'name' => 'Barcaza '],
            ['id' => 874, 'code' => 'NBB ', 'name' => 'Número De Bobinas '],
            ['id' => 875, 'code' => 'NC ', 'name' => 'Coche '],
            ['id' => 876, 'code' => 'NCL ', 'name' => 'Número De Celdas '],
            ['id' => 877, 'code' => 'ND ', 'name' => 'Barril Neto '],
            ['id' => 878, 'code' => 'NE ', 'name' => 'Litro Neto '],
            ['id' => 879, 'code' => 'NEW ', 'name' => 'Newton '],
            ['id' => 880, 'code' => 'NF ', 'name' => 'Mensaje '],
            ['id' => 881, 'code' => 'NG ', 'name' => 'Galón Neto (Nosotros) '],
            ['id' => 882, 'code' => 'NH ', 'name' => 'Hora Del Mensaje '],
            ['id' => 883, 'code' => 'NI ', 'name' => 'Galón Imperial Neto '],
            ['id' => 884, 'code' => 'NIU ', 'name' => 'Número De Unidades Internacionales '],
            ['id' => 885, 'code' => 'NJ ', 'name' => 'Número De Pantallas '],
            ['id' => 886, 'code' => 'NL ', 'name' => 'Carga '],
            ['id' => 887, 'code' => 'MNI ', 'name' => 'Milla Nautica '],
            ['id' => 888, 'code' => 'NMP ', 'name' => 'Número De Paquetes '],
            ['id' => 889, 'code' => 'NN ', 'name' => 'Entrenar '],
            ['id' => 890, 'code' => 'NPL ', 'name' => 'Número De Parcelas '],
            ['id' => 891, 'code' => 'NPR ', 'name' => 'Numero De Pares '],
            ['id' => 892, 'code' => 'TNP ', 'name' => 'Numero De Partes '],
            ['id' => 893, 'code' => 'NQ ', 'name' => 'Mho '],
            ['id' => 894, 'code' => 'NR ', 'name' => 'Micromho '],
            ['id' => 895, 'code' => 'NRL ', 'name' => 'Número De Rollos '],
            ['id' => 896, 'code' => 'NT ', 'name' => 'Tonelada Neta '],
            ['id' => 897, 'code' => 'NTT ', 'name' => 'Registro Neto De Toneladas '],
            ['id' => 898, 'code' => 'NU ', 'name' => 'Medidor De Newton '],
            ['id' => 899, 'code' => 'NV ', 'name' => 'Vehículo '],
            ['id' => 900, 'code' => 'NX ', 'name' => 'Parte Por Mil '],
            ['id' => 901, 'code' => 'NY ', 'name' => 'Libra Por Aire Seco Tonelada Métrica '],
            ['id' => 902, 'code' => 'OA ', 'name' => 'Panel '],
            ['id' => 903, 'code' => 'OHM ', 'name' => 'Ohm '],
            ['id' => 904, 'code' => 'EN ', 'name' => 'Onza Por Yarda Cuadrada '],
            ['id' => 905, 'code' => 'ONZ ', 'name' => 'Onza '],
            ['id' => 906, 'code' => 'OP ', 'name' => 'Dos Paquetes '],
            ['id' => 907, 'code' => 'OT ', 'name' => 'Hora Extra '],
            ['id' => 908, 'code' => 'OZA ', 'name' => 'Onza Líquida (Us) '],
            ['id' => 909, 'code' => 'OZI ', 'name' => 'Onza Líquida (Reino Unido) '],
            ['id' => 910, 'code' => 'P0 ', 'name' => 'Pagina – Electronica '],
            ['id' => 911, 'code' => 'P1 ', 'name' => 'Por Ciento '],
            ['id' => 912, 'code' => 'P2 ', 'name' => 'Libra Por Pie '],
            ['id' => 913, 'code' => 'P3 ', 'name' => 'Paquete De Tres '],
            ['id' => 914, 'code' => 'P4 ', 'name' => 'Paquete De Cuatro '],
            ['id' => 915, 'code' => 'P5 ', 'name' => 'Paquete De Cinco '],
            ['id' => 916, 'code' => 'P6 ', 'name' => 'Paquete De Seis '],
            ['id' => 917, 'code' => 'P7 ', 'name' => 'Paquete De Siete '],
            ['id' => 918, 'code' => 'P8 ', 'name' => 'Paquete De Ocho '],
            ['id' => 919, 'code' => 'P9 ', 'name' => 'Paquete De Nueve '],
            ['id' => 920, 'code' => 'PA ', 'name' => 'Paquete '],
            ['id' => 921, 'code' => 'PAL ', 'name' => 'Pascal '],
            ['id' => 922, 'code' => 'PB ', 'name' => 'Par De Pulgadas '],
            ['id' => 923, 'code' => 'PD ', 'name' => 'Almohadilla '],
            ['id' => 924, 'code' => 'PE ', 'name' => 'Equivalente En Libras '],
            ['id' => 925, 'code' => 'PF ', 'name' => 'Palet (Ascensor) '],
            ['id' => 926, 'code' => 'PG ', 'name' => 'Plato '],
            ['id' => 927, 'code' => 'PGL ', 'name' => 'Galón De Prueba '],
            ['id' => 928, 'code' => 'Pi ', 'name' => 'Tono '],
            ['id' => 929, 'code' => 'PK ', 'name' => 'Paquete '],
            ['id' => 930, 'code' => 'PL ', 'name' => 'Cubo '],
            ['id' => 931, 'code' => 'PM ', 'name' => 'Porcentaje De Libra '],
            ['id' => 932, 'code' => 'PN ', 'name' => 'Libra Neta '],
            ['id' => 933, 'code' => 'PO ', 'name' => 'Libra Por Pulgada De Longitud '],
            ['id' => 934, 'code' => 'PQ ', 'name' => 'Página Por Pulgada '],
            ['id' => 935, 'code' => 'par ', 'name' => 'Pr '],
            ['id' => 936, 'code' => 'PT ', 'name' => 'Pinta '],
            ['id' => 937, 'code' => 'PTD ', 'name' => 'Pinta Seca '],
            ['id' => 938, 'code' => 'PTI ', 'name' => 'Pinta (Reino Unido) '],
            ['id' => 939, 'code' => 'PTL ', 'name' => 'Pinta Liquida (Us) '],
            ['id' => 940, 'code' => 'PU ', 'name' => 'Bandeja / Paquete De Bandeja '],
            ['id' => 941, 'code' => 'PV ', 'name' => 'Media Pinta (Us) '],
            ['id' => 942, 'code' => 'PW ', 'name' => 'Libra Por Pulgada De Ancho '],
            ['id' => 943, 'code' => 'PY ', 'name' => 'Peck Dry (Us) '],
            ['id' => 944, 'code' => 'PZ ', 'name' => 'Peck Dry (Reino Unido) '],
            ['id' => 945, 'code' => 'Q3 ', 'name' => 'Comida '],
            ['id' => 946, 'code' => 'QA ', 'name' => 'Página – Facsímil '],
            ['id' => 947, 'code' => 'QAN ', 'name' => 'Cuarto (De Un Año) '],
            ['id' => 948, 'code' => 'QB ', 'name' => 'Página – Copia Impresa '],
            ['id' => 949, 'code' => 'QD ', 'name' => 'Cuarto De Docena '],
            ['id' => 950, 'code' => 'QH ', 'name' => 'Un Cuarto De Hora '],
            ['id' => 951, 'code' => 'QK ', 'name' => 'Cuarto De Kilogramo '],
            ['id' => 952, 'code' => 'QR ', 'name' => 'Mano De Papel '],
            ['id' => 953, 'code' => 'QT ', 'name' => 'Cuarto De Galón (Us) '],
            ['id' => 954, 'code' => 'QTD ', 'name' => 'Cuarto Seco (Ee. Uu.) '],
            ['id' => 955, 'code' => 'QTI ', 'name' => 'Cuarto De Galón (Reino Unido) '],
            ['id' => 956, 'code' => 'QTL ', 'name' => 'Cuarto Líquido (Us) '],
            ['id' => 957, 'code' => 'QTR ', 'name' => 'Cuarto (Uk) '],
            ['id' => 958, 'code' => 'R1 ', 'name' => 'Pica '],
            ['id' => 959, 'code' => 'R4 ', 'name' => 'Caloría '],
            ['id' => 960, 'code' => 'R9 ', 'name' => 'Mil Metros Cúbicos '],
            ['id' => 961, 'code' => 'RA ', 'name' => 'Estante '],
            ['id' => 962, 'code' => 'RD ', 'name' => 'Barra '],
            ['id' => 963, 'code' => 'RG ', 'name' => 'Anillo '],
            ['id' => 964, 'code' => 'RH ', 'name' => 'Hora De Funcionamiento O De Funcionamiento '],
            ['id' => 965, 'code' => 'RK ', 'name' => 'Medida Métrica Rollo '],
            ['id' => 966, 'code' => 'RL ', 'name' => 'Carrete '],
            ['id' => 967, 'code' => 'RM ', 'name' => 'Resma '],
            ['id' => 968, 'code' => 'RN ', 'name' => 'Medida Métrica De Resma '],
            ['id' => 969, 'code' => 'RO ', 'name' => 'Rodar '],
            ['id' => 970, 'code' => 'RP ', 'name' => 'Libra Por Resma '],
            ['id' => 971, 'code' => 'RPM ', 'name' => 'Revoluciones Por Minuto '],
            ['id' => 972, 'code' => 'RPS ', 'name' => 'Revoluciones Por Segundo '],
            ['id' => 973, 'code' => 'RS ', 'name' => 'Reiniciar '],
            ['id' => 974, 'code' => 'RT ', 'name' => 'Ingreso Tonelada Milla '],
            ['id' => 975, 'code' => 'RU ', 'name' => 'Correr '],
            ['id' => 976, 'code' => 'S3 ', 'name' => 'Pie Cuadrado Por Segundo '],
            ['id' => 977, 'code' => 'S4 ', 'name' => 'Metro Cuadrado Por Segundo '],
            ['id' => 978, 'code' => 'S5 ', 'name' => 'Sesenta Cuartos De Pulgada '],
            ['id' => 979, 'code' => 'S6 ', 'name' => 'Sesión '],
            ['id' => 980, 'code' => 'S7 ', 'name' => 'Unidad De Almacenamiento '],
            ['id' => 981, 'code' => 'S8 ', 'name' => 'Unidad De Publicidad Estándar '],
            ['id' => 982, 'code' => 'SA ', 'name' => 'Saco '],
            ['id' => 983, 'code' => 'SAN ', 'name' => 'Medio Año (6 Meses) '],
            ['id' => 984, 'code' => 'OCS ', 'name' => 'Puntuación '],
            ['id' => 985, 'code' => 'SCR ', 'name' => 'Escrúpulo '],
            ['id' => 986, 'code' => 'SD ', 'name' => 'Libra Solida '],
            ['id' => 987, 'code' => 'SE ', 'name' => 'Sección '],
            ['id' => 988, 'code' => 'SEC ', 'name' => 'Segundo '],
            ['id' => 989, 'code' => 'SET ', 'name' => 'Conjunto '],
            ['id' => 990, 'code' => 'SG ', 'name' => 'Segmento '],
            ['id' => 991, 'code' => 'SHT ', 'name' => 'Tonelada De Envío '],
            ['id' => 992, 'code' => 'SIE ', 'name' => 'Siemens '],
            ['id' => 993, 'code' => 'SK ', 'name' => 'Camión Cisterna Dividido '],
            ['id' => 994, 'code' => 'SL ', 'name' => 'Hoja De Deslizamiento '],
            ['id' => 995, 'code' => 'SMI ', 'name' => 'Milla (Milla Estatutaria) '],
            ['id' => 996, 'code' => 'SN ', 'name' => 'Varilla Cuadrada '],
            ['id' => 997, 'code' => 'SO ', 'name' => 'Carrete '],
            ['id' => 998, 'code' => 'SP ', 'name' => 'Paquete De Estante '],
            ['id' => 999, 'code' => 'SQ ', 'name' => 'Cuadrado '],
            ['id' => 1000, 'code' => 'SR ', 'name' => 'Tira '],
            ['id' => 1001, 'code' => 'SS ', 'name' => 'Hoja Métrica Medida '],
            ['id' => 1002, 'code' => 'SST ', 'name' => 'Corto Estándar (7200 Partidos) '],
            ['id' => 1003, 'code' => 'ST ', 'name' => 'Hoja '],
            ['id' => 1004, 'code' => 'ITS ', 'name' => 'Piedra (Reino Unido) '],
            ['id' => 1005, 'code' => 'STN ', 'name' => 'Tonelada (Us) O Tonelada Corta (Uk / Us) '],
            ['id' => 1006, 'code' => 'SV ', 'name' => 'Patinar '],
            ['id' => 1007, 'code' => 'SX ', 'name' => 'Envío '],
            ['id' => 1008, 'code' => 'T0 ', 'name' => 'Línea De Telecomunicaciones En Servicio. '],
            ['id' => 1009, 'code' => 'T1 ', 'name' => 'Mil Libras Brutas '],
            ['id' => 1010, 'code' => 'T3 ', 'name' => 'Mil Piezas '],
            ['id' => 1011, 'code' => 'T4 ', 'name' => 'Bolsa De Mil '],
            ['id' => 1012, 'code' => 'T5 ', 'name' => 'Caja De Mil '],
            ['id' => 1013, 'code' => 'T6 ', 'name' => 'Mil Galones (Us) '],
            ['id' => 1014, 'code' => 'T7 ', 'name' => 'Mil Impresiones '],
            ['id' => 1015, 'code' => 'T8 ', 'name' => 'Mil Pulgadas Lineales '],
            ['id' => 1016, 'code' => 'TA ', 'name' => 'Décimo Pie Cúbico '],
            ['id' => 1017, 'code' => 'TAH ', 'name' => 'Kiloampere Hora (Mil Amperios Hora) '],
            ['id' => 1018, 'code' => 'TC ', 'name' => 'Camion '],
            ['id' => 1019, 'code' => 'TD ', 'name' => 'Termia '],
            ['id' => 1020, 'code' => 'TE ', 'name' => 'Totalizador '],
            ['id' => 1021, 'code' => 'TF ', 'name' => 'Diez Metros Cuadrados '],
            ['id' => 1022, 'code' => 'TI ', 'name' => 'Mil Pulgadas Cuadradas '],
            ['id' => 1023, 'code' => 'TJ ', 'name' => 'Mil Centímetros Cuadrados '],
            ['id' => 1024, 'code' => 'TK ', 'name' => 'Tanque, Rectangular '],
            ['id' => 1025, 'code' => 'TL ', 'name' => 'Mil Pies (Lineales) '],
            ['id' => 1026, 'code' => 'TN ', 'name' => 'Estaño '],
            ['id' => 1027, 'code' => 'TNE ', 'name' => 'Tonelada (Tonelada Métrica) '],
            ['id' => 1028, 'code' => 'TP ', 'name' => 'Paquete De Diez '],
            ['id' => 1029, 'code' => 'TPR ', 'name' => 'Diez Pares '],
            ['id' => 1030, 'code' => 'TQ ', 'name' => 'Mil Pies '],
            ['id' => 1031, 'code' => 'TQD ', 'name' => 'Mil Metros Cúbicos Por Día '],
            ['id' => 1032, 'code' => 'TR ', 'name' => 'Diez Pies Cuadrados '],
            ['id' => 1033, 'code' => 'TRL ', 'name' => 'Trillón (Eur) '],
            ['id' => 1034, 'code' => 'TS ', 'name' => 'Mil Pies Cuadrados '],
            ['id' => 1035, 'code' => 'TSD ', 'name' => 'Tonelada De Sustancia 90% Seca '],
            ['id' => 1036, 'code' => 'TSH ', 'name' => 'Tonelada De Vapor Por Hora '],
            ['id' => 1037, 'code' => 'TT ', 'name' => 'Mil Metros Lineales '],
            ['id' => 1038, 'code' => 'TU ', 'name' => 'Tubo '],
            ['id' => 1039, 'code' => 'TV ', 'name' => 'Mil Kilogramos '],
            ['id' => 1040, 'code' => 'TW ', 'name' => 'Mil Hojas '],
            ['id' => 1041, 'code' => 'TY ', 'name' => 'Tanque, Cilíndrico '],
            ['id' => 1042, 'code' => 'U1 ', 'name' => 'Tratamiento '],
            ['id' => 1043, 'code' => 'U2 ', 'name' => 'Tableta '],
            ['id' => 1044, 'code' => 'UA ', 'name' => 'Torr '],
            ['id' => 1045, 'code' => 'UB ', 'name' => 'Línea De Telecomunicaciones En Servicio Promedio. '],
            ['id' => 1046, 'code' => 'UC ', 'name' => 'Puerto De Telecomunicaciones '],
            ['id' => 1047, 'code' => 'UD ', 'name' => 'Décimo Minuto '],
            ['id' => 1048, 'code' => 'UE ', 'name' => 'Décima Hora '],
            ['id' => 1049, 'code' => 'UF ', 'name' => 'Uso Por Línea De Telecomunicación Promedio '],
            ['id' => 1050, 'code' => 'UH ', 'name' => 'Diez Mil Yardas '],
            ['id' => 1051, 'code' => 'UM ', 'name' => 'Millones De Unidades '],
            ['id' => 1052, 'code' => 'VA ', 'name' => 'Voltio Amperio Por Kilogramo '],
            ['id' => 1053, 'code' => 'VI ', 'name' => 'Frasco '],
            ['id' => 1054, 'code' => 'VLT ', 'name' => 'Voltio '],
            ['id' => 1055, 'code' => 'VQ ', 'name' => 'Abultar '],
            ['id' => 1056, 'code' => 'VS ', 'name' => 'Visitar '],
            ['id' => 1057, 'code' => 'W2 ', 'name' => 'Kilo Mojado '],
            ['id' => 1058, 'code' => 'W4 ', 'name' => 'Dos Semanas '],
            ['id' => 1059, 'code' => 'WA ', 'name' => 'Vatio Por Kilogramo '],
            ['id' => 1060, 'code' => 'WB ', 'name' => 'Libra Mojada '],
            ['id' => 1061, 'code' => 'WCD ', 'name' => 'Cable '],
            ['id' => 1062, 'code' => 'WE ', 'name' => 'Tonelada Mojada '],
            ['id' => 1063, 'code' => 'WEB ', 'name' => 'Weber '],
            ['id' => 1064, 'code' => 'WEE ', 'name' => 'Semana '],
            ['id' => 1065, 'code' => 'WG ', 'name' => 'Galon De Vino '],
            ['id' => 1066, 'code' => 'WH ', 'name' => 'Rueda '],
            ['id' => 1067, 'code' => 'WHR ', 'name' => 'Vatios Hora '],
            ['id' => 1068, 'code' => 'WI ', 'name' => 'Peso Por Pulgada Cuadrada '],
            ['id' => 1069, 'code' => 'WM ', 'name' => 'Mes De Trabajo '],
            ['id' => 1070, 'code' => 'WR ', 'name' => 'Envolver '],
            ['id' => 1071, 'code' => 'WSD ', 'name' => 'Estándar Servicios '],
            ['id' => 1072, 'code' => 'WTT ', 'name' => 'Vatio '],
            ['id' => 1073, 'code' => 'WW ', 'name' => 'Mililitro De Agua '],
            ['id' => 1074, 'code' => 'X1 ', 'name' => 'Cadena '],
            ['id' => 1075, 'code' => 'YDK ', 'name' => 'Yarda Cuadrada '],
            ['id' => 1076, 'code' => 'YDQ ', 'name' => 'Yarda Cúbica '],
            ['id' => 1077, 'code' => 'YL ', 'name' => 'Cien Yardas Lineales '],
            ['id' => 1078, 'code' => 'YRD ', 'name' => 'Yarda '],
            ['id' => 1079, 'code' => 'YT ', 'name' => 'Diez Yardas '],
            ['id' => 1080, 'code' => 'Z1 ', 'name' => 'Van De Elevación '],
            ['id' => 1081, 'code' => 'Z2 ', 'name' => 'Pecho '],
            ['id' => 1082, 'code' => 'Z3 ', 'name' => 'Barril '],
            ['id' => 1083, 'code' => 'Z4 ', 'name' => 'Pipa '],
            ['id' => 1084, 'code' => 'Z5 ', 'name' => 'Arrastrar '],
            ['id' => 1085, 'code' => 'Z6 ', 'name' => 'Punto De Conferencia '],
            ['id' => 1086, 'code' => 'Z8 ', 'name' => 'Línea De Noticias De Ágata '],
            ['id' => 1087, 'code' => 'ZP ', 'name' => 'Página '],
            ['id' => 1088, 'code' => 'ZZ ', 'name' => 'Mutuamente Definido '],


        ]);
    }
}
